### ISSUE TITLE
Wrong font

### ISSUE THREAD

**Issue by georgemac70cr8** [asgiom/cr8-brm-mobile-issues#1]
I don't think the font in the app is the official Montserrat font used in the style guide. Please change all text in the app to the correct font.

**Comment by t3nshi** [comment]
Ok, thanks for noticing, I will check right away, I don't know how this would happen, I set up the font from the beginning, it should be the right font. I will let you know when it is fixed.

**Comment by t3nshi** [comment]
You where right due to a typo the fonts were not assigned properly, this is solved now for next testing version

**Comment by t3nshi** [comment]
I could tell from one screenshot you posted that this was cleared and no longer a issue. I will close it, If you think something was left out please open it again.
