### ISSUE TITLE
[BUG] Change pin 

### ISSUE THREAD

**Issue by ibanezvaio** [asgiom/cr8-brm-mobile-issues#100]
**Describe the bug**

**To Reproduce**
1. Go to Settings
 - ensure biometric is enabled
2. Click on [Change Pin] 
3. Enter the requested details (email, new pin, pin confirmation)
4. Tap [Change Pin]<- app is slow to respond here. I had to keep tapping [Change Pin] for it to respond
5. When biometric is requested, ensure this fails
6. See screenshot with "Enter PIN to authorise PIN modification"
7. Cancel button does not work here
8. Closing and reopening the app does not resolve the issue as Biometric fails 
9. Only way to get access again is uninstalling and recovering the wallet from Seed words

PIN modification I assume happening in the background. It appears that biometric correlates to the Pin and when the change is requested, the Pin is changed but not authorised in step 3 above, leaving the app in an orphaned state.

**Expected behavior**
No modification should occur until biometric is authorised 

**Screenshots**
![image0 (2)](https://user-images.githubusercontent.com/2853264/93329309-e8621d80-f814-11ea-9b09-3a5b786086d3.png)

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS:  iOS
 - OS Version 14.0
 - App Version 0.5.4

**Additional context**

**Comment by t3nshi** [comment]
Yes, it seems that this is not really the bug but the same behavior you reported earlier when the biometric gets cancelled. #90 
another thing is that this is not going to behave well when we have biometrics enabled since biometrics disable the pin. So I will look into only providing this option with biometrics disabled

**Comment by danielwwf** [comment]
Not fixed :(

**Comment by t3nshi** [comment]
can you provide details? did you tested on v 0.5.5 ? what happened and on what device? we checked by the steps provided on ios device and simulator and with the fix for handling the error it was resolved.

**Comment by ibanezvaio** [comment]
My bad, I’ve updated the original description for a better understanding. There was a critical step missing that i couldn’t capture ( I was locked out because of the bug). 

Tested in 0.5.5 @t3nshi

**Comment by t3nshi** [comment]
thanks for making the steps more precise... I will make sure to test with this steps again to reproduce the error. Again, I think we should only allow changing the PIN when you already disabled the biometrics... but let's check this out.

**Comment by ibanezvaio** [comment]
Pin change is only allowed to occur when biometrics is disabled. Fixed in 0.5.6
