### ISSUE TITLE
VERY IMPORTANT: ADD TEXT TO TERMS OF SERVICE

### ISSUE THREAD

**Issue by georgemac70cr8** [asgiom/cr8-brm-mobile-issues#101]
**Terms Of Service document changes**
We need a section of text added to the Terms of Service to reduce / mitigate our damage from disgruntled players. Highly important. Text inluded here and screenshot to give context. Plus word doc attached with the text highlighted in yellow.

**Reason**
Without this added to the the content, we may be liable to a large number of complaints and personal claims.

**Description**
Please add this text to the Terms of Service:

**CR8 Wallet Buying and Selling Crazy8Token**

Any purchase of Crazy8Token, whether it be via a crypto currency or a fiat currency (government issued currency), directly within the CR8 Wallet has a resale expiration period of no more than seven (7) days after purchase. Any attempts of selling Crazy8Token holdings purchased more than 7 days prior in the CR8 Wallet will not be possible. The resale of Crazy8Token will be accepted under the following circumstances: when the sell back is within seven (7) days of the original purchase; is in the same currency as the original purchase; and is no more than the original purchase value (calculated in USD).

If you are not permitted to sell back Crazy8Token holdings directly in your CR8 Wallet, crypto exchanges are available for you to sell your Crazy8Token.

<img width="571" alt="Screenshot 2020-09-18 at 13 10 32" src="https://user-images.githubusercontent.com/69824025/93592519-9e16a300-f9b2-11ea-8b64-fda67bf72794.png">

**Screenshots**
screenshot attached to give context and where it goes in the ToS.
[Full_TermsofService_final.docx](https://github.com/asgiom/cr8-brm-mobile-issues/files/5245190/Full_TermsofService_final.docx)

**Comment by t3nshi** [comment]
Sure, I will add it then for the upcoming version.

**Comment by danielwwf** [comment]
fixed and added to the website
