### ISSUE TITLE
[BUG]No way of baypassing biometrics

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#102]
**Describe the bug**
You can not bypass biometrics.

**To Reproduce**
1. Enable biometrics
2. Try to login without biometrics

**Expected behavior**
There should be a "Use PIN instead" option

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/93643533-7a7a4980-fa00-11ea-8a02-619184663433.png)

**Smartphone (please complete the following information):**
ALL

**Additional context**

**Comment by t3nshi** [comment]
It's weird... when we try to enroll like you... with no biometrics enrolled, the system gives the same error alert, but with a title and a button to USE PIN... so we so far were unable to reproduce this issue. Both on android and on ios we were able to fallback to PIN when we enable biometrics and we did not have biometrics or we have no finger or face enrolled. Can you maybe give us a little more info on how to reproduce? is this only happening on this iPhone?

**Comment by t3nshi** [comment]
I could reproduce the issue both on device and in simulator. The thing is that after you enable the biometric and completely shut down the app and reopen it... the tap on login triggers the alert you sent first, and we get stucked. If you just log out and log in you will get an option to use pin. So the good news is that I can try to solve it from there.

**Comment by danielwwf** [comment]
The bypass now triggers biometrics to be switched off, that's kind of okay for now
