### ISSUE TITLE
[UI-FIX]Change PIN shows CSC Logo

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#103]
**Section or interface element**
Change PIN should not show the CSC logo

![image](https://user-images.githubusercontent.com/30388756/93646156-f4f99800-fa05-11ea-8694-1edb5cd8aa9e.png)

**Comment by t3nshi** [comment]
That's right.

**Comment by danielwwf** [comment]
fixed
