### ISSUE TITLE
[BUG]Change PIN asks for email

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#104]
**Describe the bug**
Change PIN asks for email even though there seems to be no validation of it.

**To Reproduce**
1. Go to change the pin

**Expected behavior**
The email should not be needed to change your pin

**Screenshots**

![image](https://user-images.githubusercontent.com/30388756/93646252-26726380-fa06-11ea-868f-26478b14fbee.png)

**Smartphone (please complete the following information):**
ALL

**Comment by t3nshi** [comment]
You are right. This is actually not needed here since we do store the user email on the user, the validation in place was done actually once on the process since the crypto of the PIN uses also the email.  I will fix it for next version.

**Comment by danielwwf** [comment]
fixed
