### ISSUE TITLE
[UI-FIX]Wording on "Send Unavailbale"

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#105]
**Section or interface element**
Please change the wording to the following:

Heading: "Send unavailable"
Main text: "Please purchase transactions prior to sending."

Add a [?] according to screen 2 that links to: https://crazy8token.com/transactions/

**Screenshots**

Screen 1
![image](https://user-images.githubusercontent.com/30388756/93647676-3f304880-fa09-11ea-80a2-c279d55925fd.png)

Screen 2
![image](https://user-images.githubusercontent.com/30388756/93648359-e366bf00-fa0a-11ea-9610-c2c3d330f2ee.png)

**Comment by t3nshi** [comment]
Lol... sure what do you think about "Sending disabled" or "Can't send"

**Comment by t3nshi** [comment]
regarding the ? link, I cannot really add it like you presented here... but I could add another button to the alert actions... something like  "More info"?

**Comment by t3nshi** [comment]
![Screenshot 2020-09-21 at 11 33 20](https://user-images.githubusercontent.com/3123415/93794873-49676800-fbfe-11ea-9385-821591425e44.png)
maybe something like this...

**Comment by danielwwf** [comment]
The more info thing is fine. However, the wording hasn't been changed. pls change the wording according to the initial request:

**Comment by t3nshi** [comment]
Well actually it was changed..  now it says "Sending not possible" and before it was "Send unavailable"  and by the way, if you have some wording in mind would you please share it? I am not very good with telepathy these days. :)

**Comment by t3nshi** [comment]
We will check if the next version comply to the requirements.

**Comment by danielwwf** [comment]
closed
