### ISSUE TITLE
[BUG][BACKEND][CR8] KYC status not shown

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#107]
**Describe the bug**
KYC status is not visible in the CR8 backend.

**To Reproduce**
1. Go to Users
2. See error

**Expected behavior**
The indicator for KYC status should show the status of a users KYC

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/93709225-e06beb80-fb3c-11ea-9437-141a9f0bd425.png)

**Comment by viktorhugo** [comment]
En cr8 it does not show the status of the user kyc, it can be verified in opibis. (this field will be deleted)
