### ISSUE TITLE
A way to cancel sending a transaction at pin entry

### ISSUE THREAD

**Issue by ibanezvaio** [asgiom/cr8-brm-mobile-issues#11]
**Is your feature request related to a problem? Please describe.**
During sending coins, there is currently no way to cancel at the pin entry stage, meaning the only way to cancel it is to either close the app, or use the native back button (Android only, this will not be possible with iOS)

**Describe the solution you'd like**
Add a [Cancel] button somewhere during the Pin entry view

**Describe alternatives you've considered**

**Additional context**

**Comment by t3nshi** [comment]
I will take this to the team and let you know the feedback ASAP

**Comment by danielwwf** [comment]
Fixed and tested in 0.4.6.
