### ISSUE TITLE
[BUG]Getting user consent on Terms and Conditions

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#111]
**Is your feature request related to a problem? Please describe.**
We need user consent when we change the TOS

**Describe the solution you'd like**
We need to ask the user to accept the Terms and Conditions with EVERY new version.

**Comment by t3nshi** [comment]
Are you sure you want it on every update and not just when the TOS is updated?

**Comment by danielwwf** [comment]
working
