### ISSUE TITLE
[BUG]Promo Banner not loading

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#113]
**Describe the bug**
After accepting the revised TOS, the promo banner is not loading on Home.

**To Reproduce**
1. Accept updated TOS
2. See error

**Expected behavior**
Should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/93874096-23f85e00-fcd3-11ea-915e-488237daa645.png)

**Smartphone (please complete the following information):**
 - Device: Note8
 - OS: Adndroid
 - OS Version 10
 - App Version 0.5.6

**Comment by t3nshi** [comment]
I will figure it out once I reproduce it. I will let you know.

**Comment by danielwwf** [comment]
fixed.
