### ISSUE TITLE
[BUG] Wallet recovery fails -> app becomes unusable

### ISSUE THREAD

**Issue by ibanezvaio** [asgiom/cr8-brm-mobile-issues#115]
**Describe the bug**
Inputting random but valid words into the recovery screen allows you to try and recover a non-existing account. When it fails, the app has wiped the existing wallet and becomes fairly unusable

**To Reproduce**
1. Create a wallet or ensure one is active
2. Log out
3. Tap [recover wallet]
4. Enter random words - ensure word validation is green for all
5. enter email
6. Tap [Set a Pin]
7. enter pin and continue
8. When recovery fails, it will take you back to the home screen displaying [Create new wallet] and [Recover Wallet]
9. Try tapping [Create new wallet] or [Recover wallet] in this state and the app becomes very buggy with display issues and sometimes unresponsive

**Expected behavior**
Existing wallet should only be removed when wallet recovery is confirmed. If recovery fails, the app should maintain the previous wallet i.e. the home screen should still allow login to the existing wallet

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS
 - OS Version 14.0
 - App Version 0.5.6

**Additional context**

**Comment by t3nshi** [comment]
this sounded very similar to #18, but when I attentively read again I realize that this present the problem only when it fails... So I will see how it is working and what can I gather to fix it... Thanks for reporting! well spotted.

**Comment by t3nshi** [comment]
Can you please check this and validate solution?

**Comment by ibanezvaio** [comment]
Yes, this kind of does fix the issue. The app is a little jumpy (reported in another issue a while back I believe) following failure to recover but otherwise seems functional
