### ISSUE TITLE
[UI-FIX] Font smaller in dark then in light theme

### ISSUE THREAD

**Issue by t-jacobi** [asgiom/cr8-brm-mobile-issues#118]
**Section or interface element**
Switching to dark theme changes the font to a smaller one then on light theme

**Reason**
Because the font on dark theme is to small

**Description**
It should be the same font and font size like in the light theme. 

**Screenshots**
![IMG_4358](https://user-images.githubusercontent.com/46750418/93925253-2af49000-fd16-11ea-8ab2-2ab9d5321120.png)
![IMG_4359](https://user-images.githubusercontent.com/46750418/93925323-43fd4100-fd16-11ea-9e1d-6bdf2ae598f7.png)

** System **
iPhone 6s 13.6

**Comment by t3nshi** [comment]
Nice one... it seems that on the dark mode is not rendering the right font. Thanks for reporting.

**Comment by t-jacobi** [comment]
Fixed on 0.5.8!
