### ISSUE TITLE
[Backend] Coinpayments AccountID always treated as mandatory

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#12]
**Describe the bug**
Coinpayments AccountID always treated is always mandatory even if the DepositType is manual or Direct.

**To Reproduce**
1. Go to Operator Profile Details
2. Delete the "1" in Coinpayments AccountID, click save

**Expected behavior**
If the type is anything else the coinpayments the field should not be mandatory.

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/90576010-2b50b700-e1bd-11ea-8e0c-84b9688b7a25.png)

**Comment by t3nshi** [comment]
I will check and let you know.

**Comment by t3nshi** [comment]
After some tests on TESTNET, I can see that the field is mandatory ONLY when you have selected the coinpayments DepositType, as it should be... if you change the DepositType to other than coinpayments you can delete the coinpayments accountID, but if you have coinpayments as DepositType coinpayments accountid is mandatory.
