### ISSUE TITLE
[BUG] Allow only decimal and specific special chars for "amount" fields.

### ISSUE THREAD

**Issue by t-jacobi** [asgiom/cr8-brm-mobile-issues#121]
**Describe the bug**
You can enter alphanumerical characters into the amount field in the area of sending and recieving.
Also the keyboard layout should be the same in this two areas. (Send: direct numerical, recieve: alpha layout)

**To Reproduce**
1. Go to 'Send
2. Click on Amount
3. Switch to alpha characters 

or

1. Go to 'Recieve'
2. Click on Amount
3. Alpha keyboard layout will be shown

**Expected behavior**
Allow only numbers and , and . 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 6s
 - OS: iOS
 - OS Version 13.6.1
 - App Version 0.5.6

**Additional context**
This solves a unrealstic issue but looks professional IMO.

**Comment by t3nshi** [comment]
Thatś right the implementation is for numeric, but it seems that numeric also allows hexadecimal in the HTML5 ref. I will check that. Thanks for noticing.

**Comment by t-jacobi** [comment]
I can confirm that this is done on 0.5.8
