### ISSUE TITLE
[ADD]: Automatically update QR code while typing

### ISSUE THREAD

**Issue by t-jacobi** [asgiom/cr8-brm-mobile-issues#122]
**Is your feature request related to a problem? Please describe.**
You're creating a QR code with all data on it but you need to click on "update qr code" after enter the data.
This can lead to an issue during the process of sharing the qr code because people cant human read that code.

**Describe the solution you'd like**
After each change in this fields you should recreate the qr code and remove the update button. So its always in a current state. 

**Describe alternatives you've considered**
i dont think there is an alternate

**Additional context**

**Comment by t3nshi** [comment]
I will check if with some changes we made before we can introduce this feature again without producing ANR state... if we can I will let you know.

**Comment by t-jacobi** [comment]
works perfect on 0.5.8
