### ISSUE TITLE
[REQUEST]Remove all CSC related assets

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#129]
Remove all CSC related assets -> cr8-brm-mobile/src/assets/, replace with CR8 related assets.

There should not be a single graphic related to CSC anywhere

**Comment by t3nshi** [comment]
What are you talking about... If this is a bug please make it reproducible so we can test and figure it out... Otherwise with something  so general and unespecific I won't be able to address it or even validate solution... Thanks.

**Comment by danielwwf** [comment]
Check the source code as mentioned above, we cant test the app day in day out just to find another CSC asset as they are still there. 

Just check ALL assets and if they are CSC related, REMOVE them. Have a look at cr8-brm-mobile/src/assets/ its full of BRM graphics

**Comment by Mattch33** [comment]
![image](https://user-images.githubusercontent.com/65967421/94020670-17dfcf80-fdab-11ea-87f3-8e71ee219516.png)

**Comment by t3nshi** [comment]
This is on which app version.

**Comment by Mattch33** [comment]
![Uploading image.png…]()

**Comment by Mattch33** [comment]
![image](https://user-images.githubusercontent.com/65967421/94021332-ce43b480-fdab-11ea-960b-fd592d019032.png)

**Comment by t3nshi** [comment]
I saw it on the original issue... for the future it will be quicker to just reference the issue like this #128

**Comment by Mattch33** [comment]
I don't think we should go down the route of discussing speed. Please do as requested.

**Comment by t3nshi** [comment]
I'm sorry. I was only trying to be helpful but clearly I wasn't.

**Comment by georgemac70cr8** [comment]
this has now been corrected but let's just make sure it is still correct on 0.5.8

**Comment by t3nshi** [comment]
this was validated by several users already, only issue was still with testflight users, as it seems that there was a caching of icons from previous versions. But in it was reported on #128  that it was only a little buggy on testflight on 0.5.8 but it was resolved. It is very functional both on 0.5.8 and 0.5.9. So I will be closing this now.
