### ISSUE TITLE
[BUG][IMPORTANT]Gender selection

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#131]
**Describe the bug**
**In order to pass Apples review, we need to make the gender selection optional!**

**Comment by t3nshi** [comment]
Thank for noticing... it will be implemented for next version

**Comment by t-jacobi** [comment]
on iOS 13.6.1 with 0.5.8 it was optional now.

**Comment by amadorj23** [comment]
Is gender not KYC requirement on every government ID?

**Comment by danielwwf** [comment]
fixed.
