### ISSUE TITLE
FULL TERMS OF SERVICE ON INITIAL LAUNCH

### ISSUE THREAD

**Issue by georgemac70cr8** [asgiom/cr8-brm-mobile-issues#14]
TERMS OF SERVICE section

IS IT POSSIBLE TO HAVE THE "I AGREE" CHECK BOX AND THE CONTINUE BUTTON MOVED TO THE TOP OF THE PAGE (so the player doesn't need to scroll all the way down to the foot of the page)? Or is that a regulation that we must adhere to?

Also, strange change in background colour going from white to grey on my phone (huawei p20 pro) - see in the attached screenshot.

Please change the wording from "**This** Terms of Service has been revised as of xxxxx" to "**The** Terms of Service..." - and in regular, not italic. BOLD IS HERE JUST TO ILLUSTRATE, DO NOT DO BOLD ON THE ACTUAL DOCUMENT ITSELF.

"I have read, understand and accept the disclaimer" to "I have read, **I** understand and **I** accept the disclaimer."

![Screenshot_20200819_115426_com opibis cr8 mobile](https://user-images.githubusercontent.com/69824025/90622301-36cfcc80-e215-11ea-96be-272c3927e3ed.jpg)

**CAN YOU PLEASE ATTACH THE FULL TERMS OF SERVICE IN A TEXT / WORD FILE SO THAT I CAN GO THROUGH AND DOUBLCHECK THE FULL DOC. THERE IS STRANGE LAYOUT IN SOME SECTIONS (LARGE DOUBLE SPACING) AS WELL AS "casinocoin" reference. I will send back with tracked changes.**

**Comment by t3nshi** [comment]
Of course, very clear changes and straightforward... as for moving the "I agree" check and "continue" and button to top, you must consult this with your legal and I will do as they instruct.  Many disclaimers use some measures to make sure the user goes through a document before clicking accept because in case of litigation this measures will act in favor of the company, and against of  scam-like behaviours that could be alleged by some user (For example a page shows itself as being something that is not and put an invisible and tiny disclaimer that almost everyone is going to miss).

**Comment by t3nshi** [comment]
> CAN YOU PLEASE ATTACH THE FULL TERMS OF SERVICE IN A TEXT / WORD FILE SO THAT I CAN GO THROUGH AND DOUBLCHECK THE FULL DOC. THERE IS STRANGE LAYOUT IN SOME SECTIONS (LARGE DOUBLE SPACING) AS WELL AS "casinocoin" reference. I will send back with tracked changes.

yes sure, but the format was already provided by @whywefight in HTML,  so there is no such double spacing, it is just that when you justify a text, sometimes it leaves some spacing when a large word was wrapped to next line.
This is the full text (with the format as it was provided)

``` html
<h2>Terms of Service</h2>
<p style="text-align: justify;">These Terms of Service (“Terms”) apply to your access to, and use of, the Opibis OÜ and or Crazy8Token products and services (“Services”) available through our website (“Website”) and or apps ("Software"). Opibis OÜ (“Opibis”) owns and operates the Software, Website, and provides the Services to you in accordance with the terms and conditions set out below.</p>
<p style="text-align: justify;">We reserve the right to change or modify the terms and conditions contained in these Terms or any policy or guideline of the Software and Website, at any time and in our sole discretion. We will provide notice of these changes by posting the revised Terms to the Software and Website and changing the “Last Revised” date at the bottom of the Terms, or by providing other means of notice as Opibis will determine each time in its sole discretion. Any changes or modifications will be effective immediately upon publishing the revisions to the Software and Website and will apply to your subsequent use of the Software and Website. Your continued use of this Software and Website will confirm your acceptance of such changes or modifications; therefore, you should review the Terms and applicable policies whenever you use the Software and Website to understand the terms that apply to such use.</p>
<p style="text-align: justify;">The most current version of the Terms can be reviewed by clicking on the “Terms of Service” hypertext link located at the bottom of our web pages and via the About Section in the Software. If you do not agree to the Terms in effect when you access or use the Software and Website, you must stop using the Software and Website. We reserve the right to withdraw or amend the Services without notice, and at any time whatsoever.</p>
<p style="text-align: justify;"><strong>Privacy Policy</strong></p>
<p style="text-align: justify;">Our privacy policy, which sets out how we will use your information, can be found at https://opibis.com/privacy-policy/. By using the Software and Website, you consent to the processing described therein and warrant that all data provided by you is accurate.</p>
<p style="text-align: justify;"><strong>Use of the Software and Website</strong></p>
<p style="text-align: justify;">You agree to access and use the Software and Website and or the Services in accordance with these Terms and any guidelines set out on our Software and Website. You will not: (a) commit or encourage a criminal offense; (b) transmit or distribute a virus, trojan, worm, logic bomb or any other material which is malicious, technologically harmful, in breach of confidence or in any way offensive or obscene; (c) hack into any aspect of the Services; (d) corrupt data; (e) cause annoyance to other users; (f) infringe upon the rights of any other person’s proprietary rights; (g) send any unsolicited advertising or promotional material, commonly referred to as “spam”; or attempt to affect the performance or functionality of any computer facilities of or accessed through this Software and Website.</p>
<p style="text-align: justify;">Breaching this provision would constitute a criminal offense and Opibis will report any such breach to the relevant law enforcement authorities and disclose your identity to them.</p>
<p style="text-align: justify;">Opibis will not be liable for any loss or damage caused by a distributed denial-of-service attack, viruses or other technologically harmful material that may infect your computer equipment, computer programs, data or other proprietary material due to your use of this Software and Website, the Services, or to your downloading of any material posted on it, or on any website linked to it.</p>
<p style="text-align: justify;"><strong>CR8 Wallet</strong></p>
<p style="text-align: justify;">If you wish to use the CR8 Wallet, you must create an account (“Account”) to access the wallet Services (“Wallet”). When you create a Wallet, you are strongly advised to take the following precautions, as failure to do so may result in loss of access to, and/or control over, your Wallet: (a) create a PIN that you do not use for any other website or online service; (b) Provide accurate and truthful information; (c) Maintain and promptly update your Wallet information; (d) Maintain the security of your Wallet by protecting your Wallet PIN and access to your device and your Wallet; (e) Promptly notify us if you discover or otherwise suspect any security breaches related to your Wallet and/or Account; and (f) Use the ‘Export Private Keys’ and/or ‘Generate Paper Wallet’ functionality provided by the Wallet and safeguard your backup files and seeds as you would safeguard your most important personal information.</p>
<p style="text-align: justify;">You hereby accept and acknowledge that you take responsibility for all activities that occur under your Account and/or Wallet and accept all risks of any authorized or unauthorized access to your Account and/or Wallet, to the maximum extent permitted by law.</p>
<p style="text-align: justify;"><strong>Intellectual Property, Software and Content</strong></p>
<p style="text-align: justify;">The intellectual property rights in all software and content (including photographic images) made available to you on or through this Website remains the property of Opibis or its licensors and are protected by copyright laws and treaties around the world. All such rights are reserved by Opibis and its licensors. You may store, print, and display the content supplied solely for your own personal use. You are not permitted to publish, manipulate, distribute or otherwise reproduce, in any format, any of the content or copies of the content supplied to you or which appears on this Website nor may you use any such content in connection with any business or commercial enterprise. Your access to, and use of, our content is at your sole risk.</p>
<p style="text-align: justify;"><strong>Linking to our Website</strong></p>
<p style="text-align: justify;">You may link to our home page, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it, but you must not establish a link in such a way as to suggest any form of association, approval or endorsement on our part where none exists. You must not establish a link from any website that is not owned by you. This Website must not be framed on any other site, nor may you create a link to any part of this Website other than the home page. We reserve the right to withdraw linking permission without notice in our sole discretion.</p>
<p style="text-align: justify;"><strong>Third-Party Content Disclaimer</strong></p>
<p style="text-align: justify;">In using our Services, you may view content or utilize services provided by third parties, including links to web pages and services of such parties, including, without limitation, coin exchanges (“Third Party Content”). We do not control, endorse or adopt any Third Party Content and will have no responsibility for Third-Party Content including, without limitation, material that may be misleading, incomplete, erroneous, offensive, indecent or otherwise objectionable in your jurisdiction.</p>
<p style="text-align: justify;">Further, your dealings or correspondence with such third parties are solely between you and any such third parties. We are not responsible or liable for any loss or damage of any sort whatsoever incurred as a result of any such dealings and you understand that your use of Third Party Content, and your interactions with third parties, is at your own risk.</p>
<p style="text-align: justify;">Any third party trademarks or trade names featured on this Website are owned by the respective trademark owners. Where a trademark or brand name is referred to it is used solely to describe or identify the products and services and is in no way an assertion that such products or services are endorsed by or connected to CasinoCoin.</p>
<p style="text-align: justify;"><strong>Disclaimer of Liability</strong></p>
<p style="text-align: justify;">OPIBIS PROVIDES NO GUARANTEE AS TO THE PERFORMANCE OR THE UNINTERRUPTED AVAILABILITY OF THE SOFTWARE AND WEBSITE OR THE SERVICES. THE SOFTWARE AND WEBSITE AND SERVICES ARE PROVIDED ON AN “AS IS,” “AS AVAILABLE” BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. OPIBIS DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT AS TO THE SOFTWARE AND WEBSITE AND THE INFORMATION, CONTENT, AND MATERIALS CONTAINED THEREIN. OPIBIS DOES NOT REPRESENT OR WARRANT THAT THE SERVICES OR THE WEBSITE ARE ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE. WHILE OPIBIS ATTEMPTS TO MAKE YOUR ACCESS AND USE OF THE WEBSITE SAFE, OPIBIS CANNOT AND DOES NOT REPRESENT OR WARRANT THAT THE SOFTWARE AND WEBSITE OR ITS SERVER(S) ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; THEREFORE, YOU SHOULD USE INDUSTRY-RECOGNIZED SOFTWARE TO DETECT AND DISINFECT VIRUSES FROM ANY DOWNLOAD.</p>
<p style="text-align: justify;">Some jurisdictions do not allow the disclaimer of implied terms in contracts with consumers, so some or all of the disclaimers in this section may not apply to you.</p>
<p style="text-align: justify;"><strong>Indemnity</strong></p>
<p style="text-align: justify;">You agree to indemnify, defend and hold harmless Opibis, its directors, officers, employees, consultants, agents, and affiliates, from any and all third party claims, liability, damages and costs (including, but not limited to, legal fees) arising from your use this Website, the Services, or your breach of the Terms of Service.</p>
<p style="text-align: justify;"><strong>Variation, Suspension or Termination</strong></p>
<p style="text-align: justify;">Opibis shall have the right, in its sole discretion, at any time and without notice, to amend, remove or vary the Services and/or any page of the Software and Website. Further, Opibis reserves the right, without notice and in its sole discretion, to terminate or suspend your right to use the Software and Website and/or the Services, and to block or prevent your future access to, and use of, the Website and/or the Services.</p>
<p style="text-align: justify;"><strong>Governing Law and Jurisdiction</strong></p>
<p style="text-align: justify;">These Terms of Service shall be governed and construed solely in accordance with the laws of Estonia without giving effect to its conflicts of law principles. You agree that the Estonia courts shall have exclusive jurisdiction in relation to any claim, dispute, or difference concerning these Terms of Service.</p>
<p style="text-align: justify;"><strong>Invalidity</strong></p>
<p style="text-align: justify;">If any provision of these Terms shall be declared by any court of competent jurisdiction to be illegal, void or unenforceable, all other provisions of these Terms of Service shall not be affected and shall remain in full force and effect.</p>
<p style="text-align: justify;"><strong>Waiver</strong></p>
<p style="text-align: justify;">If you breach these Terms and we take no action, we will still be entitled to use our rights and remedies in any other situation where you breach these Terms of Service.</p>
<p style="text-align: justify;"><strong>Entire Agreement</strong></p>
<p style="text-align: justify;">The above Terms of Service constitute the entire agreement between you and us and will supersede any and all prior or contemporaneous agreements between you and Opibis.</p>
<p style="text-align: justify;"><strong>Contact Us</strong></p>
<p style="text-align: justify;">If you have any questions or concerns, please contact us at support@opibis.com</p>
<p style="text-align: justify;">The Terms of Service has been revised as of July 23, 2020</p>
```

**Comment by danielwwf** [comment]
I just put the whole code in an html viewer and it looks good, the issue is clearly with the wallet. George is working on the edits and will provide the code in the next hour. 
![image](https://user-images.githubusercontent.com/30388756/90764262-5c79d600-e2e8-11ea-8a7d-4db8152f94ab.png)

**Comment by georgemac70cr8** [comment]
I don't have the answers, all i know is that it looks good on an online desktop html viewer but not on my phone. So it needs to be changed so it doesn't look like it does on mobile. Is this html5 optmised?

Spacing looks bad on a phone and there is no line break between headings on my phone. 

huawei phone view...
![Screenshot_20200820_132529_com opibis cr8 mobile](https://user-images.githubusercontent.com/69824025/90764925-6d771700-e2e9-11ea-8778-bf07becabd7b.jpg)

html viewer...
<img width="828" alt="Screenshot 2020-08-20 at 13 26 11" src="https://user-images.githubusercontent.com/69824025/90765088-a3b49680-e2e9-11ea-9d01-4d4dac715484.png">

It is obvious to see the difference (excepting different font).

**Comment by georgemac70cr8** [comment]
modified Terms of Service HTML with some text changes...

<h2>Terms of Service</h2>
<p style="text-align: justify;">These Terms of Service (“Terms”) apply to your access to, and use of, the Opibis OÜ and or Crazy8Token products and services (“Services”) available through our website (“Website”) and or apps ("Software"). Opibis OÜ (“Opibis”) owns and operates the Software, Website, and provides the Services to you in accordance with the terms and conditions set out below.</p>
<p style="text-align: justify;">We reserve the right to change or modify the terms and conditions contained in these Terms or any policy or guideline of the Software and Website, at any time and in our sole discretion. We will provide notice of these changes by posting the revised Terms to the Software and Website and changing the “Last Revised” date at the bottom of the Terms, or by providing other means of notice as Opibis will determine each time in its sole discretion. Any changes or modifications will be effective immediately upon publishing the revisions to the Software and Website and will apply to your subsequent use of the Software and Website. Your continued use of this Software and Website will confirm your acceptance of such changes or modifications; therefore, you should review the Terms and applicable policies whenever you use the Software and Website to understand the terms that apply to such use.</p>
<p style="text-align: justify;">The most current version of the Terms can be reviewed by clicking on the “Terms of Service” hypertext link located at the bottom of our web pages and via the About Section in the Software. If you do not agree to the Terms in effect when you access or use the Software and Website, you must stop using the Software and Website. We reserve the right to withdraw or amend the Services without notice, and at any time whatsoever.</p>
<p style="text-align: justify;"><strong>Privacy Policy</strong></p>
<p style="text-align: justify;">Our privacy policy, which sets out how we will use your information, can be found at https://opibis.com/privacy-policy/. By using the Software and Website, you consent to the processing described therein and warrant that all data provided by you is accurate.</p>
<p style="text-align: justify;"><strong>Use of the Software and Website</strong></p>
<p style="text-align: justify;">You agree to access and use the Software and Website and or the Services in accordance with these Terms and any guidelines set out on our Software and Website. You will not: (a) commit or encourage a criminal offense; (b) transmit or distribute a virus, trojan, worm, logic bomb or any other material which is malicious, technologically harmful, in breach of confidence or in any way offensive or obscene; (c) hack into any aspect of the Services; (d) corrupt data; (e) cause annoyance to other users; (f) infringe upon the rights of any other person’s proprietary rights; (g) send any unsolicited advertising or promotional material, commonly referred to as “spam”; or attempt to affect the performance or functionality of any computer facilities of or accessed through this Software and Website.</p>
<p style="text-align: justify;">Breaching this provision would constitute a criminal offense and Opibis will report any such breach to the relevant law enforcement authorities and disclose your identity to them.</p>
<p style="text-align: justify;">Opibis will not be liable for any loss or damage caused by a distributed denial-of-service attack, viruses or other technologically harmful material that may infect your computer equipment, computer programs, data or other proprietary material due to your use of this Software and Website, the Services, or to your downloading of any material posted on it, or on any website linked to it.</p>
<p style="text-align: justify;"><strong>CR8 Wallet</strong></p>
<p style="text-align: justify;">If you wish to use the CR8 Wallet, you must create an account (“Account”) to access the wallet Services (“Wallet”). When you create a Wallet, you are strongly advised to take the following precautions, as failure to do so may result in loss of access to, and/or control over, your Wallet: (a) create a PIN that you do not use for any other website or online service; (b) Provide accurate and truthful information; (c) Maintain and promptly update your Wallet information; (d) Maintain the security of your Wallet by protecting your Wallet PIN and access to your device and your Wallet; (e) Promptly notify us if you discover or otherwise suspect any security breaches related to your Wallet and/or Account; and (f) Use the ‘Export Private Keys’ and/or ‘Generate Paper Wallet’ functionality provided by the Wallet and safeguard your backup files and seeds as you would safeguard your most important personal information.</p>
<p style="text-align: justify;">You hereby accept and acknowledge that you take responsibility for all activities that occur under your Account and/or Wallet and accept all risks of any authorized or unauthorized access to your Account and/or Wallet, to the maximum extent permitted by law.</p>
<p style="text-align: justify;"><strong>Intellectual Property, Software and Content</strong></p>
<p style="text-align: justify;">The intellectual property rights in all software and content (including photographic images) made available to you on or through this Website remains the property of Opibis or its licensors and are protected by copyright laws and treaties around the world. All such rights are reserved by Opibis and its licensors. You may store, print, and display the content supplied solely for your own personal use. You are not permitted to publish, manipulate, distribute or otherwise reproduce, in any format, any of the content or copies of the content supplied to you or which appears on this Website nor may you use any such content in connection with any business or commercial enterprise. Your access to, and use of, our content is at your sole risk.</p>
<p style="text-align: justify;"><strong>Linking to our Website</strong></p>
<p style="text-align: justify;">You may link to our home page, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it, but you must not establish a link in such a way as to suggest any form of association, approval or endorsement on our part where none exists. You must not establish a link from any website that is not owned by you. This Website must not be framed on any other site, nor may you create a link to any part of this Website other than the home page. We reserve the right to withdraw linking permission without notice in our sole discretion.</p>
<p style="text-align: justify;"><strong>Third-Party Content Disclaimer</strong></p>
<p style="text-align: justify;">In using our Services, you may view content or utilize services provided by third parties, including links to web pages and services of such parties, including, without limitation, coin exchanges (“Third Party Content”). We do not control, endorse or adopt any Third Party Content and will have no responsibility for Third-Party Content including, without limitation, material that may be misleading, incomplete, erroneous, offensive, indecent or otherwise objectionable in your jurisdiction.</p>
<p style="text-align: justify;">Further, your dealings or correspondence with such third parties are solely between you and any such third parties. We are not responsible or liable for any loss or damage of any sort whatsoever incurred as a result of any such dealings and you understand that your use of Third Party Content, and your interactions with third parties, is at your own risk.</p>
<p style="text-align: justify;">Any Third Party trademarks or trade names featured in the Software and or on the Website are owned by the respective trademark owners. Where a trademark or brand name is referred to it is used solely to describe or identify the products and services and is in no way an assertion that such products or services are endorsed by or connected to Opibis.</p>
<p style="text-align: justify;"><strong>Disclaimer of Liability</strong></p>
<p style="text-align: justify;">OPIBIS PROVIDES NO GUARANTEE AS TO THE PERFORMANCE OR THE UNINTERRUPTED AVAILABILITY OF THE SOFTWARE AND WEBSITE OR THE SERVICES. THE SOFTWARE AND WEBSITE AND SERVICES ARE PROVIDED ON AN “AS IS,” “AS AVAILABLE” BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. OPIBIS DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT AS TO THE SOFTWARE AND WEBSITE AND THE INFORMATION, CONTENT, AND MATERIALS CONTAINED THEREIN. OPIBIS DOES NOT REPRESENT OR WARRANT THAT THE SERVICES OR THE WEBSITE ARE ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE. WHILE OPIBIS ATTEMPTS TO MAKE YOUR ACCESS AND USE OF THE WEBSITE SAFE, OPIBIS CANNOT AND DOES NOT REPRESENT OR WARRANT THAT THE SOFTWARE AND WEBSITE OR ITS SERVER(S) ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; THEREFORE, YOU SHOULD USE INDUSTRY-RECOGNIZED SOFTWARE TO DETECT AND DISINFECT VIRUSES FROM ANY DOWNLOAD.</p>
<p style="text-align: justify;">Some jurisdictions do not allow the disclaimer of implied terms in contracts with consumers, so some or all of the disclaimers in this section may not apply to you.</p>
<p style="text-align: justify;"><strong>Indemnity</strong></p>
<p style="text-align: justify;">You agree to indemnify, defend and hold harmless Opibis, its directors, officers, employees, consultants, agents, and affiliates, from any and all third party claims, liability, damages and costs (including, but not limited to, legal fees) arising from your use this Website, the Services, or your breach of the Terms of Service.</p>
<p style="text-align: justify;"><strong>Variation, Suspension or Termination</strong></p>
<p style="text-align: justify;">Opibis shall have the right, in its sole discretion, at any time and without notice, to amend, remove or vary the Services and/or any page of the Software and Website. Further, Opibis reserves the right, without notice and in its sole discretion, to terminate or suspend your right to use the Software and Website and/or the Services, and to block or prevent your future access to, and use of, the Website and/or the Services.</p>
<p style="text-align: justify;"><strong>Governing Law and Jurisdiction</strong></p>
<p style="text-align: justify;">These Terms of Service shall be governed and construed solely in accordance with the laws of Estonia without giving effect to its conflicts of law principles. You agree that the Estonia courts shall have exclusive jurisdiction in relation to any claim, dispute, or difference concerning these Terms of Service.</p>
<p style="text-align: justify;"><strong>Invalidity</strong></p>
<p style="text-align: justify;">If any provision of these Terms shall be declared by any court of competent jurisdiction to be illegal, void or unenforceable, all other provisions of these Terms of Service shall not be affected and shall remain in full force and effect.</p>
<p style="text-align: justify;"><strong>Waiver</strong></p>
<p style="text-align: justify;">If you breach these Terms and we take no action, we will still be entitled to use our rights and remedies in any other situation where you breach these Terms of Service.</p>
<p style="text-align: justify;"><strong>Entire Agreement</strong></p>
<p style="text-align: justify;">The above Terms of Service constitute the entire agreement between you and us and will supersede any and all prior or contemporaneous agreements between you and Opibis.</p>
<p style="text-align: justify;"><strong>Contact Us</strong></p>
<p style="text-align: justify;">If you have any questions or concerns, please contact us at support@opibis.com</p>
<p style="text-align: justify;">The Terms of Service has been revised as of August 20, 2020.</p>

**Comment by t3nshi** [comment]
I'm not sure if with this exercise you already understood what creates the problem or not, so I will explain a bit:https://user-
![Screenshot 2020-08-20 at 08 46 25](https://user-images.githubusercontent.com/3123415/90778078-d185e500-e2c1-11ea-97d5-a50ccaa7a891.png)
When you see those ugly spaces is because the text is justified, and let's take this example, and that line, the next word won't fit the current line, so it gets wrapped to next line, and since is justified paragraph all word distribute evenly, and to accomplish that the spaces need to widen a bit creating the ugly effect. In wide screens is not a problem, since a large word is really a small percentage of a line, in a narrow width, some words make up to 20% or 30% of the lenght of a line creating this problem.
So viewing it in wide screens does not make this a problem of the app, since the app will be viewed on narrow screens... If you open the app on a tablet you will be able to see that the ugly spaces are not there anymore.

**Comment by georgemac70cr8** [comment]
so why not not justify then? what does it look like without justification?

**Comment by georgemac70cr8** [comment]
does that explain linebreak and headings?

**Comment by t3nshi** [comment]
> so why not not justify then? what does it look like without justification? 

I will use your corrections... and will show you some screenshots so you can decide which fits bets

> does that explain linebreak and headings?

No, html is semantic markup, as pointing up what is a header and what is a paragraph... but the style, margins and other things needs to be provided additionally, so I will try something for the spaces on the headings and from the screenshots you will tell me what you think

**Comment by t3nshi** [comment]
I Made a lot of adjusments and broke into pieces the text so I could give some styles inside the app instead of taking the default html formatting. So here are a couple of screenshots so we get some idea and decide:
-- this is with left alignment:

![Screenshot 2020-08-20 at 17 40 32](https://user-images.githubusercontent.com/3123415/90833011-b5f3fc00-e30c-11ea-903a-54ae87a6c556.png)

-- this is with justfied paragraph

![Screenshot 2020-08-20 at 17 41 15](https://user-images.githubusercontent.com/3123415/90833013-b68c9280-e30c-11ea-8b10-95cdad2bb94c.png)

-- this is with alignment to the center.

![Screenshot 2020-08-20 at 17 41 52](https://user-images.githubusercontent.com/3123415/90833015-b7bdbf80-e30c-11ea-85e4-8793bdc8260b.png)

**Comment by georgemac70cr8** [comment]
Just an fyi, the terms of service I've added here still need to be replaced on the apk so that the mention of casinocoin is removed and replaced by Opibis. And I also updated the last revised date at the footer.

**Comment by t3nshi** [comment]
> Just an fyi, the terms of service I've added here still need to be replaced on the apk so that the mention of casinocoin is removed and replaced by Opibis. And I also updated the last revised date at the footer.

Yes the examples above are done with the edited text you provided... but you still haven't said if we should use one or the other...

**Comment by georgemac70cr8** [comment]
Can we have left alignment with headings also left aligned?

**Comment by t3nshi** [comment]
It looks like this

![Screenshot 2020-08-21 at 08 52 30](https://user-images.githubusercontent.com/3123415/90898058-b4b5e400-e38b-11ea-9db8-a674f7d9b827.png)

**Comment by georgemac70cr8** [comment]
i think that's better, thanks. let's go with that. i'll let you close the issue when complete.

**Comment by t3nshi** [comment]
Great thanks! As soon as I solve the camera issue I will push this also into a new version.
