### ISSUE TITLE
RECOVER WALLET PROBLEM

### ISSUE THREAD

**Issue by georgemac70cr8** [asgiom/cr8-brm-mobile-issues#18]
**Describe the bug**
george tried to recover wallet after setting up a wallet but it didn't recover. It just left me hanging for around 5 mins until i had to close down the app

**To Reproduce**
1. open app
2. press 'recover wallet'
3. enter the recovery phrases
4. input pin

**Expected behavior**
it should recover the other wallet but it was just processing for some time until i needed to close down the app externally

**Screenshots**

**Smartphone (please complete the following information):**
huawei p20 pro
![photo_2020-08-19 13 17 45](https://user-images.githubusercontent.com/69824025/90628714-68996100-e21e-11ea-8c63-62330f905594.jpeg)

**Comment by t3nshi** [comment]
I will try to reproduce and let you know soon

**Comment by danielwwf** [comment]
This seems to happen if there is already a wallet and you want to recover one which would overwrite the current one.

**Comment by t3nshi** [comment]
That is a great insight, So I'll keep that in mind, I already tried on clean app several times and it was working ok. I will try now with an existing wallet to validate.

**Comment by danielwwf** [comment]
Issue still exists on 0.4.7

**Comment by t3nshi** [comment]
I was able to reproduce it reliably now, and thus I already found the offending code... It will be fixed for next version

**Comment by danielwwf** [comment]
The issue still exists. If try to recover an account while I already have one on my device, I end up in an infinite loop.

**Comment by t3nshi** [comment]
Ok. I already found an alternative... I will include in upcoming version

**Comment by t3nshi** [comment]
finally recovered successfully several wallets. I will include changes in upcoming version.

**Comment by t3nshi** [comment]
Please check on version 0.5.1 so we can close this

**Comment by georgemac70cr8** [comment]
i don't think this can be closed, it seems to be an issue that hasn't been fixed. please try testing by recovering a wallet when there is alerady a wallet set up. it is fine when recovering a wallet on brand new install but not after an account has been added. huawei p20.

**Comment by t3nshi** [comment]
I did that a couple of times, not on one but several devices... that's why I was asking about it. What wallet version did you check?

**Comment by georgemac70cr8** [comment]
0.5.1. i'll try again but and repeat but i think it just needs a little bit more testing.

**Comment by danielwwf** [comment]
If you recover a wallet the first time while there exists on one on the phone,  all is fine, if you try to recover the same again the issue comes up again.

**Comment by t3nshi** [comment]
So you confirmed that the issue is still present in 0.5.2?

**Comment by danielwwf** [comment]
Still present in 0.5.1

You can test this by trying to recover the same wallet multiple times

**Comment by t3nshi** [comment]
sorry yes in 0.5.1, that's the one I made several successful recoveries...

**Comment by danielwwf** [comment]
okay wiped the phone, tried this again, could successfully recover several times
