### ISSUE TITLE
RECOVERY WORD REPEATED?

### ISSUE THREAD

**Issue by georgemac70cr8** [asgiom/cr8-brm-mobile-issues#19]
**Describe the bug**
It not the most clear of pictures - taken from my facetime camera on iMac. But it looks like there's a repeat of a recovery word. I tried to restore wallet using these phrases and it said there shouldn't be repeated words.
words 2 and 6 both look like they say "loop"

**Screenshots**
attached

![Photo on 19-08-2020 at 12 41](https://user-images.githubusercontent.com/69824025/90646389-714a6100-e237-11ea-99fd-1259400409b8.jpg)

**Comment by t3nshi** [comment]
what are you trying to recover? an account from the BRM to cr8? on the token wallet and on the cr8 wallet we don't produce seeds with repeating words... so where did you get that recovery passphrase?

**Comment by georgemac70cr8** [comment]
I meant "recover wallet" not restore, as i wanted to test recover wallet process - which i have logged already because it didn't work for me.

"on the cr8 wallet we don't produce seeds with repeating words". 
that's my point - it looks like a repeated word. so if it is a repeated word in the cr8 wallet process then there's a bug. as i said, I can't be 100% certain because i wasn't asked for words 2 and 6 as verification when setting up account. but it looks like the same word twice - "loop".

This was on the cr8 wallet

**Comment by t3nshi** [comment]
After checking the code thoroughly it seems that we are allowing the generation of repeating words in some random cases. So after discussing with Andre we will make sure that the words won't be generated with duplicates. But we will allow duplicates on recovery, to make sure that these generated accounts -in the past when we didn't have these measures- are allowed to be recovered on a wallet.

**Comment by t3nshi** [comment]
it was fixed on 0.4.7
