### ISSUE TITLE
Transaction not being fetched after setup

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#2]
**Describe the bug**
After you finished the setup the wallet won't catch any incoming transactions until gets restarted. This issue has now been fixed multiple times and reintroduced. Please quick fix this by restarting the app.

**To Reproduce**
1. Set the wallet up from scratch
2. Do not restart the app
3. Send a tx

**Expected behavior**
The wallet should detect the incoming tx

**Smartphone (please complete the following information):**
 - Device: Samsung Note8, S9+, 10
 - OS: Adnroid
 - OS Version 9 and newer
 - App Version 0.4.5

**Comment by t3nshi** [comment]
I will try to reproduce and let you know. I thought we fixed this, so I will make sure I get it right this time

**Comment by danielwwf** [comment]
fixed.
