### ISSUE TITLE
Wallet stuck on login

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#20]
**Describe the bug**
If you switch to another app and come back to the wallet after a few minutes, and the wallet locked itself, it will be stuck when you try to log in. You need to kill the app in order to get it going again.

**To Reproduce**
1. Login to the app
2. Switch to any other app without closing the wallet
3. Wait 10+ minutes
4. Try to login

**Expected behavior**
Login should work

**Smartphone (please complete the following information):**
 - Device: Samsung Note8, S9+, 10 
 - OS: Android
 - OS Version 9 and newer
 - App Version 0.4.6

**Comment by t3nshi** [comment]
It didn't happened to me for a while... until just about an hour ago... I thought that it was proof... but then I realized that that phone was not connected to the internet... :/ I will try to reproduce somehow. If you find a reliable way to produce this issue let me know.

**Comment by danielwwf** [comment]
trying to reproduce on several devices while recording a video
