### ISSUE TITLE
[BUG] Casino's list becomes blank

### ISSUE THREAD

**Issue by moatazkhalifa** [asgiom/cr8-brm-mobile-issues#24]
**Describe the bug**
After using the app for a bit, 'Casinos' list gets stuck like the screenshot below

**To Reproduce**
1. Use the app for a few mins
2. Move around the different tabs

**Screenshot**

![Screenshot_20200819-183507_CR8 Wallet](https://user-images.githubusercontent.com/60157931/90664364-1e7aa480-e24b-11ea-898c-c861af086795.jpg)

**Smartphone**
 - Device: Samsung S9+
 - OS: Android 10
- Version 46

**Comment by t3nshi** [comment]
Did you have the casinos shown previously? did you grant access to location? Is your location (GPS) on?

**Comment by moatazkhalifa** [comment]
> Did you have the casinos shown previously? did you grant access to location? Is your location (GPS) on?

Yes location is on (it's always on). Previously it said no Casinos to show. Daniel was going to check if Egypt was allowed for listing casinos

**Comment by t3nshi** [comment]
let me know what happens if you close the app and open it again.

**Comment by moatazkhalifa** [comment]
If I close the app and re-open, it seems fine. Then after a while, I get that.

**Comment by danielwwf** [comment]
Egypt in the allowed list of countries, at least one should be shown on startup.
![image](https://user-images.githubusercontent.com/30388756/90675763-31957080-e25b-11ea-9a10-67e383c467b9.png)

**Comment by moatazkhalifa** [comment]
Okay, then issue #16 applies to me as well.

**Comment by t3nshi** [comment]
That's weird... I will try to replicate somehow... it would help that you provide all the info that makes this happen, if you realize it at all..

**Comment by moatazkhalifa** [comment]
Sorry no clue

**Comment by t3nshi** [comment]
Since this is a Samsung device, I will say that it is related to what's discussed on #16, Let's close this since the focus there is on these devices.
