### ISSUE TITLE
[UI-FIX] Adding a new contact

### ISSUE THREAD

**Issue by moatazkhalifa** [asgiom/cr8-brm-mobile-issues#25]
When adding a new contact, 'Add new contact' is cut off. Please increase container size or change text to 'Add new'

Cannot take screenshot for some reason

**Comment by t3nshi** [comment]
Are you sure? can you provide a screenshot? I tried in many phones, some with small screens and still looks ok to me
![image](https://user-images.githubusercontent.com/3123415/90670980-a5af2480-e219-11ea-9fda-0537e6cac0b9.png)

**Comment by moatazkhalifa** [comment]
I'm sure yes. I couldn't take a screenshot, it takes me to the previous screen for some reason. 

Device is Samsung S9+ Android 10

**Comment by danielwwf** [comment]
Samsung Note8

![image](https://user-images.githubusercontent.com/30388756/90676278-0bbc9b80-e25c-11ea-89a7-97a8a0e4212d.png)

**Comment by moatazkhalifa** [comment]
Could this be related to using that weird font? We should have Montserrat instead

**Comment by t3nshi** [comment]
LOL! That font is exaclty montserrat. George made me realize that it was not applied and I spent a big chunk of the day yesterday making it work, I downloaded the fonts, converted to other formats and prepared the snippets so it will work and after some trial and error I had it working.

**Comment by moatazkhalifa** [comment]
It's not applied all over the app. Most of the text is not. This was ok in previous versions, and got messed up on this one

**Comment by t3nshi** [comment]
the previous versions were with the issue... they were appling helvetica on iphone and roboto on Android.... don't take my word for it... simply compare a script with the selected families of Montserrat from the manual, with these screenshots and with some older screenshots and you will see.

**Comment by moatazkhalifa** [comment]
The App's font is definitely not Montserrat. See how https://crazy8token.com/ looks and you'll see the difference

**Comment by t3nshi** [comment]
Was this supposed to look different how? What I see is the same typeface... what I should be looking at?

**Comment by moatazkhalifa** [comment]
![90670980-a5af2480-e219-11ea-9fda-0537e6cac0b9](https://user-images.githubusercontent.com/60157931/90692071-bf318a00-e274-11ea-93f4-0dd9cfeca223.png)

**Comment by t3nshi** [comment]
So... your point?

**Comment by t3nshi** [comment]
To make this explicit and clear, especially for future reference, according to our previous chat, I will change all the main titles and buttons that had 900 boldness and secondary titles that had 600 as instructed in the manual, to 500 boldness for titles and buttons, and 400 for regular text. Take into account that it could be simpler to make the request direct and explicit that left me trying to figure out what you are thinking or what you wanted.  This change I think I will like because the superbold text is ugly, but personally I did not like everything squary, I liked better the roundy buttons and containers. But hey, that just me!

**Comment by moatazkhalifa** [comment]
Cool titles and buttons should have 500 weight and 400 for regular text. Thanks

**Comment by t3nshi** [comment]
All this  was done a while ago... So it will be up for a short while after the next version and then I will close it if there are no updates.

**Comment by moatazkhalifa** [comment]
Tested on 49 and it still looks the same

**Comment by t3nshi** [comment]
When you say 49 you mean 0.4.9? and when you say it looks the same, you mean that we still have the fonts that are not Montserrat but they are but with wrong font weight? If you are not going to be specific on things I will not be able to give you a proper fix. Try to compose at least a sentence marking if something still needs fixing, what that is. When I check on several devices I see what was described here fixed.  Thanks for your consideration.

**Comment by moatazkhalifa** [comment]
Yes on version 0.4.9. 

Font is ok. I'm referring to the original issue: When adding a new contact, 'Add new contact' is cut off. as per the screenshot at the top

**Comment by moatazkhalifa** [comment]
Still having the same issue on latest version.  'Add new contact' is cut off

**Comment by t3nshi** [comment]
Did you test on version 0.5.1 already? seems not, since the text was changed and it does not say that anymore

**Comment by t3nshi** [comment]
Please test on 0.5.2 and let us now if it's fixed now.

**Comment by moatazkhalifa** [comment]
It's been changed to 'Add New' so it's all good now. Closing this
