### ISSUE TITLE
[UI-FIX] When auto-fill is used, a blue box is visible behind the text

### ISSUE THREAD

**Issue by moatazkhalifa** [asgiom/cr8-brm-mobile-issues#27]
Moved from Sheet.

![image](https://user-images.githubusercontent.com/30388756/90676023-9650cb00-e25b-11ea-86d2-1d943da8ce6c.png)

**Comment by t3nshi** [comment]
Yes, as you are aware this is a known issue, and there is still no solution yet. I will update if we find anything that might solve this.

**Comment by moatazkhalifa** [comment]
Fixed on 0.5.5
