### ISSUE TITLE
[UI-FIX] OPIBIS screen scrolling 

### ISSUE THREAD

**Issue by moatazkhalifa** [asgiom/cr8-brm-mobile-issues#29]
OPIBIS screen does not fit to the window, there are vertical and horizontal bars. See screenshot below

![Screenshot_20200819-205411_CR8 Wallet](https://user-images.githubusercontent.com/60157931/90678368-e7ae8980-e25e-11ea-8ffa-3353cae467a4.jpg)

I would assume this is an iframe, if that's the case then you may find the below solution helpful:

`<iframe src="" scrolling="no"></iframe>
`

You could also combine it with another solution via CSS:

`iframe {
  overflow: hidden;
}`

Device: Samsung S9+
OS: Android 10

**Comment by moatazkhalifa** [comment]
You may also want to experiment with this:

`
#Content {
 width:100%;
height:100%; 
}
`

**Comment by t3nshi** [comment]
No, no iframe, we have no control whatsoever on this cause this is the application of aver... this is the kyc opened through a plugin. All the code in here is in control of the KYC provider not us, is like opening a link in a new tab.
