### ISSUE TITLE
Text is cut off

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#3]
**Describe the bug**
On some locations like the KYC screen, the text is cut off. It seems it has nothing to do with the screen size, this happens on Note8 and Note10+, both have large screens. As you see on the screenshot there is enough space left.

**To Reproduce**
1. Do KYC

**Expected behavior**
**There has to be a solution to properly format text.** The argument of this being a "framework issue" is not good enough. We are not the only ones developing on this framework but seem to be the only party with that specific issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/90512571-a59e1e80-e15e-11ea-9fdd-1bff6ea88070.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Note8, S9+, 10 
 - OS: Android
 - OS Version 9 and newer
 - App Version 0.4.5

**Comment by t3nshi** [comment]
Ok I get what you mean. I will solve this right away!

**Comment by danielwwf** [comment]
Can't test because of https://github.com/asgiom/cr8-brm-mobile-issues/issues/8

**Comment by t3nshi** [comment]
Solved last bit for 0.4.7, was validated on 5 devices
