### ISSUE TITLE
[BACKEND][UI-FIX] Exchanges

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#35]
**Section or interface element**
Exchanges

**Reason**
Should work

**Description**
After adding an exchange, it's not shown in the wallet. Is this how it is meant to be?

**Comment by viktorhugo** [comment]
There are no exchanges yet, so for each exchange a specific configuration must be made

**Comment by t3nshi** [comment]
@viktorhugo asked me to close this. @whywefight can you see if he has proper access to edit the issues and put labels?
