### ISSUE TITLE
[UI-FIX] TOS/PP links are greyed out when tapped / Send button not aligned properly

### ISSUE THREAD

**Issue by moatazkhalifa** [asgiom/cr8-brm-mobile-issues#38]
Two issues here.

1 - PP/TOS links not formatted properly

Fix: please change the link color to #ff6500 and #fe9d0f when clicked/hovered - remove background and left padding

2 - Send button in the bottom menu is not aligned properly

Fix: please increase top margin so it's aligned with the rest of the buttons

(SEE SCREENSHOT)

![Screenshot_20200823-105736_CR8 Wallet](https://user-images.githubusercontent.com/60157931/90974894-a7395f00-e52f-11ea-9ba1-3a62322bae25.jpg)

Fix: please change the link color to #ff6500 and #fe9d0f when clicked/hovered - remove background and left padding

**Comment by t3nshi** [comment]
I was able to reproduce. Will be fixed for next version

**Comment by moatazkhalifa** [comment]
On 49, both look like buttons (they should look like links instead), and the Send button still looks the same

**Comment by t3nshi** [comment]
Can you confirm that this is fixed so we can close and move on? there is still some issue?

**Comment by moatazkhalifa** [comment]
Fixed
