### ISSUE TITLE
After KYC set, no refresh happens

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#4]
**Describe the bug**
Once KYC is passed, screen is stuck on "KYC is processing". The app needs to be restarted in order to get the buy/sell menu.

**To Reproduce**
1. Do KYC
2. Stick on screen
3. Once passed, switch do different tab and come back
4. Restart app

**Expected behavior**
After KYC is passed, the tab needs to refresh itself.

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/90512571-a59e1e80-e15e-11ea-9fdd-1bff6ea88070.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Note8, S9+, 10 
 - OS: Android
 - OS Version 9 and newer
 - App Version 0.4.5

**Comment by t3nshi** [comment]
I will fix this asap

**Comment by danielwwf** [comment]
Can't test because of https://github.com/asgiom/cr8-brm-mobile-issues/issues/8

**Comment by t3nshi** [comment]
validated on 5 devices with 0.4.7
