### ISSUE TITLE
[ADD] Open to tutorial on first launch

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#42]
**Section or interface element**
A box that asks you if you would like to read the tutorial on first launch.
Also add the link to the Help section, as first item

**Reason**
We need people to explain how the wallet wworks

**Description**
After setting the wallet up on the very first start, there should be a popup saying:

"Welcome to the CR8 Wallet! Would you like to view the tutorial?"

If clicked "No", you can use the wallet, if you click "Yes" open https://crazy8token.com/getting-started/
 
**Screenshots**
Illustrate current look and feel. Or provide commented pictures, or 
edited screens to see how it should look like. Be clear about which picture is edited

**Comment by danielwwf** [comment]
Popup happens, link in Help Menue is missing.

**Comment by t3nshi** [comment]
Great I will validate why is not appearing and fix it right away.

**Comment by danielwwf** [comment]
Also please make the option of viewing the tutorial the first one, rather than the third. Thanks :)

**Comment by t3nshi** [comment]
Ok

**Comment by danielwwf** [comment]
seems good
