### ISSUE TITLE
[BUG]Restart the wallet after setup

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#43]
**Describe the bug**
There are several issues regarding refreshing of certain areas like KYC or transactions if the wallet is used directly after setup. This is known since 0.3.7. Several attempts to fix it did not help so far. It happening on some devices but not on all. Mainly on Samsung devices.

PLEASE RESTART THE APP AFTER SETUP! This is the only working fix and won't waste any more time. We will fix this later.

**To Reproduce**
1. Set the wallet up on a Note10 
2. Send coins to wallet
3. wait for incoming tx message

**Expected behavior**
Areas like Dashboard, transactions and kyc should update after setup and login.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Note10+ and Note8
 - OS: Android
 - OS Version 10
 - App Version ALL

**Comment by danielwwf** [comment]
This will fix https://github.com/asgiom/cr8-brm-mobile-issues/issues/2

**Comment by t3nshi** [comment]
An actual restart from the code is not allowed on modern Os versions, so If what you say here is that we do the restart, that won't be possible. We can ask the user to do it.  But it still feels like an incomplete solution to me. I will try to advance on #2 so we will have this sorted out ASAP

**Comment by danielwwf** [comment]
Then tell the user the app will be closed they need to restart it and close the app when they press okay.

**Comment by danielwwf** [comment]
seems fixed
