### ISSUE TITLE
[UI-FIX]

### ISSUE THREAD

**Issue by georgemac70cr8** [asgiom/cr8-brm-mobile-issues#46]
**Section or interface element**
Initial landing page - depending on if the app has cleared data or not. 

If it's brand new app installation, the buttons say "new wallet" or "restore wallet". 
Once you have an account, when you reopen the app it says "login" or "recover wallet"

**Reason**
We need consistency - recover or restore? One, not both. 

1) Please change to "recover wallet" wherever you have an instance of "restore wallet" in the app.

2) Wrong speling of "login"

**Description**

1) Please change to "recover wallet" wherever you have an instance of "restore wallet" in the app.
2) "Login" button should be "Log In" - it's a verb, to log in (rather than login details, for example).

**Screenshots**
![Screenshot_20200831_155248_com opibis cr8 mobile](https://user-images.githubusercontent.com/69824025/91728857-fe7ca680-eba3-11ea-9405-84fddd9fbd45.jpg)
![Screenshot_20200831_155631_com opibis cr8 mobile](https://user-images.githubusercontent.com/69824025/91728868-02a8c400-eba4-11ea-8dd1-804e19f90b18.jpg)

**Comment by t3nshi** [comment]
Does the adjustments made were enough? are there still something missing?

**Comment by georgemac70cr8** [comment]
all good, thanks
