### ISSUE TITLE
[UI-FIX] receive / share account text change (remove CasinoCoin)

### ISSUE THREAD

**Issue by georgemac70cr8** [asgiom/cr8-brm-mobile-issues#47]
**Section or interface element**
Receive section > share account
when you press the share account button, it has message saying "CasinoCoin CR8 AccountID: c3E..."
Let's remove the "CasinoCoin " text and just say "CR8 Account ID: c3E..."

**Reason**
No mentions of CasinoCoin (except only the ledger or blockchain itself)

**Screenshots**
![Screenshot_20200831_180243_android](https://user-images.githubusercontent.com/69824025/91741451-05f87b80-ebb5-11ea-8c94-f96cd670c361.jpg)

**Comment by t3nshi** [comment]
will fix right away

**Comment by danielwwf** [comment]
fixed
