### ISSUE TITLE
[UI-FIX] Button text disappears after pressing

### ISSUE THREAD

**Issue by georgemac70cr8** [asgiom/cr8-brm-mobile-issues#48]
**Section or interface element**
receive > "share account" button request

**Reason**
After the button has been pressed and the action of sharing your account ID has occurred, when you go back to the receive page, the share account button now has no text written on it.

**Description**
Don't remove the text - make sure it continues to say "Share Account"

**Screenshots**
![Screenshot_20200831_180257_com opibis cr8 mobile](https://user-images.githubusercontent.com/69824025/91742040-e6158780-ebb5-11ea-9dce-35164fb9ec8a.jpg)

phone: huawei p20 pro, emui 10, android 10

**Comment by t3nshi** [comment]
I will need to have more information on this. I tried to reproduce with the information provided and it won't happen like this on 4 different devices.

**Comment by georgemac70cr8** [comment]
i can't really give you any more, you know my phone specs by now, you have the photo, you see it happens for me. glad that it might only be me.

**Comment by georgemac70cr8** [comment]
it's not a blocker comapred to the other issues like qr codes, geofencing etc

**Comment by t3nshi** [comment]
So this is happening on a huawei, right? let me check on one of those we have here...

**Comment by t3nshi** [comment]
Yeah that's it. It is happening in that huawei phone also... so that will help me solving it.

**Comment by georgemac70cr8** [comment]
Happened on another button too... "Visit" disappeared in casino section...
![Screenshot_20200901_032235_com opibis cr8 mobile](https://user-images.githubusercontent.com/69824025/91784229-aa54df00-ec02-11ea-9293-90b5e0da9213.jpg)

**Comment by t3nshi** [comment]
all white buttons will have this problem as I "fixed" these buttons for another issue ( #21 ) and the fix that worked on those phones is what is causing this here. I will see how we can fix this without breaking the other fix.

**Comment by georgemac70cr8** [comment]
It looks ike this isn't just a huawei issue but some samsungs too. attached screen shot from a different section but same problem on android

samsung galaxy s7
android version 8



![photo_2020-09-06 12 06 35](https://user-images.githubusercontent.com/69824025/92323488-7b42d100-f039-11ea-835e-68d6bd5f6498.jpeg)

**Comment by danielwwf** [comment]
The button stays selected till you tap elsewhere still.

**Comment by t3nshi** [comment]
I tried on many devices and the text doesn't disappear... If you found a new issue please close this one and open a new one.
