### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by Mattch33** [asgiom/cr8-brm-mobile-issues#49]
![Screenshot_20200831-211519_Gallery](https://user-images.githubusercontent.com/65967421/91764374-17e71800-ebcf-11ea-9e71-a873ff1e717a.jpg)

**Comment by t3nshi** [comment]
thank's, well spotted. I fixed it already.

**Comment by Mattch33** [comment]
Great, thanks.

Matt

**Comment by danielwwf** [comment]
Fixed
