### ISSUE TITLE
Buy/Sell detection does not work. Can not sell anymore

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#5]
**Describe the bug**
After buying some CR8 I immediately tried to sell them, the wallet did not recognize I had done a purchase before. On previous versions, I had to restart the app in order for the wallet to detect the buy, now this doesn't work at all.

**To Reproduce**
1. Buy CR8
2. Immediately try to sell

**Expected behavior**
After buying, selling should be possible without restarting the app

**Screenshots**

![image](https://user-images.githubusercontent.com/30388756/90517175-560f2100-e165-11ea-958c-1704c7469a73.png)
![image](https://user-images.githubusercontent.com/30388756/90517192-5d362f00-e165-11ea-816c-59e7025528b0.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Note8, S9+, 10 
 - OS: Android
 - OS Version 9 and newer
 - App Version 0.4.5

**Comment by t3nshi** [comment]
I will try to reproduce the issue now, to figure it out. But of course this should not happen.

**Comment by danielwwf** [comment]
Can't be tested because of https://github.com/asgiom/cr8-brm-mobile-issues/issues/8

**Comment by danielwwf** [comment]
Still the same. Wallet doesnt detect a buy happened, even after a restart. I will let me get a quote and push thru but is then stuck on pending.

**Comment by danielwwf** [comment]
Seems to be fixed.
