### ISSUE TITLE
[UI-FIX] - Date of Birth picker not usable

### ISSUE THREAD

**Issue by t-jacobi** [asgiom/cr8-brm-mobile-issues#53]
**Section or interface element**
Wallet creation -> Date of Birth Picker -> Font color is the same like the control background

**Reason**
I fixed the issue by my self. On iOS settings i set my iOS to dark theme that caused the issue! I set it back to light, restarted the app and the font color was black. so i could see what im doing. 

**Description**
If the iOS device is set to dark theme, the date picker should also show the font color in black. 

**Screenshots**
![IMG_4058](https://user-images.githubusercontent.com/46750418/92160148-e2d90080-ee2e-11ea-8bc9-9a95bc73a244.png)

**Smartphone**
Apple iPhone 6s (iOS 13.6.1)

**Comment by t3nshi** [comment]
....Right!, that's what is all about. Ok. I will see how we can fix it. thanks for reporting

**Comment by t3nshi** [comment]
I already found a fix... I am implementing some related changes and will do more tests. I will let you know shortly.

**Comment by danielwwf** [comment]
we need 0.5.1 on testflight to test if this was fixed.

**Comment by t3nshi** [comment]
This was fixed for last version and previous one. Please confirm so I can close this.

**Comment by danielwwf** [comment]
Fixed
