### ISSUE TITLE
[BUG] - Tutorial link goes to 404 page

### ISSUE THREAD

**Issue by t-jacobi** [asgiom/cr8-brm-mobile-issues#54]
**Describe the bug**
If you want to see the tutorial your redirected to the 404 page from crazy8token.com 

**To Reproduce**
1. Click the hamburger symbol and choose "help"
2. Click on 'Tutorial'
3. See error

**Expected behavior**
Show the tutorial

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 6s
 - OS: iOS
 - OS 13.6.1
 - App Version 0.5.0

**Additional context**

**Comment by t3nshi** [comment]
Actually the tutorial is not published yet. I am not sure but I think it was intended for tomorrow, So I will get back to you when I have any kind of confirmation.

**Comment by danielwwf** [comment]
Not published as of now
