### ISSUE TITLE
[BUG] copy tag to clipboard crashes wallet

### ISSUE THREAD

**Issue by amadorj23** [asgiom/cr8-brm-mobile-issues#55]
**Describe the bug**
When purchasing cr8 i chose xrp and when using the copy button for the tag the wallet will crash. The copy for address works without error.
**To Reproduce**
1. Go to buy/sell
2. View pending transaction
3. Click on copy button for tag

Crash

I have a video but not seeing way to upload

**Expected behavior 
Copy and paste of tag to work the same way copy and paste of address works.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhonexs
 - OS: ios
 - OS Version: 13.4.1
 - App Version: 0.5.0

**Additional context**

**Comment by t3nshi** [comment]
thanks for reporting. I will look into this and will let you know soon.

**Comment by amadorj23** [comment]
Here is video on the bug  if attachments work...

**Comment by danielwwf** [comment]
we need the app on testflight to verify this was fixed.

**Comment by t3nshi** [comment]
This should be fixed now. We tested ourselves.. please confirm.

**Comment by amadorj23** [comment]
Has an update been released to app store or test flight only?

**Comment by t3nshi** [comment]
I think test flight only

**Comment by danielwwf** [comment]
Fixed
