### ISSUE TITLE
[BACKEND] Login for new users doesnt work

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#57]
**Describe the bug**
After putting the 2fa code in and clicking submit nothing happens

**To Reproduce**
1. Create a user
2. Try to login

**Expected behavior**
Should let you log in

**Comment by t3nshi** [comment]
I am not sure if you already granted some editing rights to @viktorhugo  in the issues... so he can add labels and set milestones and more... I added him to this issue so he can give you updates.

**Comment by viktorhugo** [comment]
please specify what type of user I create: admin, operator, controller...

**Comment by danielwwf** [comment]
Currently, the issue is with admins.

**Comment by t3nshi** [comment]
this was fixed and confirmed. If it appears again please reopen.
