### ISSUE TITLE
Contacts page 

### ISSUE THREAD

**Issue by Mattch33** [asgiom/cr8-brm-mobile-issues#59]
Please add a proper address book so you can view properly rather than just on the send page.

**Comment by t3nshi** [comment]
yes, you are right, someone mentioned this before. I will see if I can add this for next upcoming version.

**Comment by danielwwf** [comment]
I came across the following issues:

Menue says "Contacts contacts" should be "Contacts"
![image](https://user-images.githubusercontent.com/30388756/92325245-535b6980-f049-11ea-9526-f546e1fdfaa6.png)

Contact name should be Black and bold, if Mo agrees
![image](https://user-images.githubusercontent.com/30388756/92325277-7f76ea80-f049-11ea-9e23-dfd5873133eb.png)

If you go back and forth you end up with an "Add new" entry. If you restart the wallet and open the contacts again, its gone.
![image](https://user-images.githubusercontent.com/30388756/92325352-1643a700-f04a-11ea-9733-52840b3b21ff.png)

There are certain combinations of back and forth which makes it stop working, ill try to figure out as many as possible,

**Comment by t3nshi** [comment]
seems to me that this issue is solved. We can keep track of UI corrections on the respective issues
