### ISSUE TITLE
Backend: Edits to operators don't get saved

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#6]
**Describe the bug**
Edit something related to an operator on the backend and hit save, nothing happens.

**To Reproduce**
1. Edit something related to an operator and hit save

**Expected behavior**
Save should work

**Comment by t3nshi** [comment]
that's not good. I will find what causes this and solve it as soon as possible!

**Comment by danielwwf** [comment]
works again.
