### ISSUE TITLE
[BUG] No Deposit Button after linking account

### ISSUE THREAD

**Issue by KickAzzDude** [asgiom/cr8-brm-mobile-issues#62]
**Describe the bug**
After linking account, clicking on the operator would not display the Deposit button until I restarted the app.

**To Reproduce**
1. Sign up to an operator
2. Go back to "Home" and click the operator you signed up for
3. No deposit button on top
4. Exit app and restart and now it shows

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - OS: Latest Android Version

**Comment by t3nshi** [comment]
Well spotted, I will try to reproduce and see what's going on. I will report back here what I find.

**Comment by t3nshi** [comment]
This was not sorted out entirely on this version moving forward

**Comment by t3nshi** [comment]
We made some fixes and after several tests we made sure that once the casino makes the callback from their side it gets updated right away via websocket.

**Comment by t3nshi** [comment]
We validated it is working and there is no response here... so I will close this... if you still have problems please reopen. thanks
