### ISSUE TITLE
[BUG] Check if an account was linked

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#64]
**Is your feature request related to a problem? Please describe.**
We are telling people to follow this to link accounts: https://crazy8token.com/linking-accounts/
We need to add something to the operator page that lets them check if the wallet knows about the destination tag, so they can compare/verify it themself.

**Describe the solution you'd like**
Add a button that says something like "verify deposit details" on the operator details and shows the deposit address + tag. or do show it right below the description.

**Comment by t3nshi** [comment]
Sounds like something we should have.. let me see how to include it for next version

**Comment by t3nshi** [comment]
Please correct me if I'm wrong but these issues are the same... #80 ... so I'm closing since it is a duplicate. If I'm wrong pleaser reopen and clarify it for me please.
