### ISSUE TITLE
[UI-FIX] copy wallet address

### ISSUE THREAD

**Issue by neilbirtles** [asgiom/cr8-brm-mobile-issues#65]
On the "Receive" page you should be able to press the address to copy it as well as the qr code - it's the address you're copying so that should let you copy on press as well

**Comment by t3nshi** [comment]
This is not clear enough, I don't understand what you are requesting. Please consider filling the entire information that is requested on the issue template. And remember that UI-FIX is for issues that want to improve UI appearance, design,  color or contrasts, and general confortable look things. when something is broken or not wroking, report a bug, when some functionality is not included or you want to do  or allow something new.. use add feature template. Thanks in advance.

**Comment by danielwwf** [comment]
He wants to be able to share the image of the QR code

**Comment by t3nshi** [comment]
Well either here and on discord he said something different... but eitherway if that is the case then that would be an enhancement and we already have the issue for that #60 ... I will close as a duplicate, If @neilbirtles believes that we are misunderstanding or that the issue presented asks for something different, please clarify and we will reopen this. Thanks.
