### ISSUE TITLE
[BUG] No notice for rejected KYC

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#67]
**Describe the bug**
If the KYC gets rejected by ever, we don't receive an update about that on the backend and the app is stuck in KYC pending.

**To Reproduce**
1. Submit KYC that will fail

**Expected behavior**
The Backend should update according to the status from aver and the wallet should offer an option to do kyc.
If a submission is rejected, it usually comes along with a reason, we need to pass that reason on to the user eg. "Unreadable Documents Or Missing Verification Information"

**Additional context**

**Comment by t3nshi** [comment]
Actually the aver callback usually reports when KYC succeeds... or when it fails.. and this is reported to the wallet to let the user know through the websocket... What you describe seems a bug on the aver part... or maybe they change something... let's wait for @viktorhugo to report back about it.

**Comment by t3nshi** [comment]
I think we will have this sorted out soon. We already implemented some changes both on back-end and wallet I am testing now to complete this.

**Comment by danielwwf** [comment]
Did submit kyc that got rejected right away, the app didn't tell me about it, even after a restart. went to the backend, refreshed the KYC manually, got the result in "rejected", no change on the app. restarted it, still telling me it's pending on the app

**Comment by t3nshi** [comment]
I will do your steps to see if I get same result.

**Comment by danielwwf** [comment]
We are now getting a message and a button to redo the KYC if it fails, but the reason is still missing. 

![image](https://user-images.githubusercontent.com/30388756/93148969-7ba43180-f6f5-11ea-9c7e-66c69579d35a.png)

If you click "Proceed To KYC" you get a screen telling you "Your KYC is pending. Please wait until approved."

Also, it should say "Proceed to KYC"

You are then stuck.

**Comment by t3nshi** [comment]
Well, I am not sure why there would be no reason, since the Aver call back usually gives the reason...  Can you provide more information about the KYC process, or what you did to get this kind of rejection so I can see what they send?

**Comment by danielwwf** [comment]
This is fixed, we are now getting a message why KYC failed.
