### ISSUE TITLE
Display for purchasing TXs

### ISSUE THREAD

**Issue by Mattch33** [asgiom/cr8-brm-mobile-issues#71]
**Section or interface element**
buy transactions

**Reason**
It's not clear that people need to pay for TX after the initial free one.  

**Description**
Can we include an indicator so people know that is why the send button is faded out. Even if we faded them all out other than the 'BUY' button 

**Screenshots**

![TX error](https://user-images.githubusercontent.com/65967421/92327875-a850ad00-f054-11ea-82f8-a7735ef5e68a.png)

**Comment by t3nshi** [comment]
Yeah that was what I was talking about several weeks ago, I don't like forms that just don't let you send but don't tell you why... but hey... so I think that one way to do it with no significant changes is an alert that pops up when you open send and have 0 tx. that offers you to go to the buy transaction page... what do you think?

**Comment by t3nshi** [comment]
on previous version 0.5.2 there was an alert added when you have 0 transactions. Please confirm that it is enough solution for the issue provided.

**Comment by danielwwf** [comment]
Works now via an alert.
