### ISSUE TITLE
[ADD] Handling for zero CSC balance

### ISSUE THREAD

**Issue by ibanezvaio** [asgiom/cr8-brm-mobile-issues#73]
**Is your feature request related to a problem? Please describe.**
When a user has a zero CSC balance, it's not obvious why CR8 cannot be sent - [Send CR8] button is greyed out

**Describe the solution you'd like**
Potentially some kind of pop-up when the greyed out [Send CR8] button is pressed to inform the user to buy a transaction package

**Comment by t3nshi** [comment]
You are right. I hate these new trend of no explanation UX, but this was requested like that, let me check with the team and try to make it more intuitive.

**Comment by t3nshi** [comment]
Actually I realized we had already an issue about it, so I will close this as a duplicate and we will keep track on this here: #71
