### ISSUE TITLE
[UI-FIX] Add link to view TX on explorer

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#75]
**Section or interface element**
Transactions -> TX details 

**Reason**
The is the industry standard.

**Description**
Need a link to csc.observer in order to view a TX on it.

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/92375285-35e9d680-f101-11ea-8883-e6cf27c6c8fc.png)

**Comment by t3nshi** [comment]
I will try to add it for next version

**Comment by danielwwf** [comment]
There is no link to the explorer

**Comment by t3nshi** [comment]
Yes there is not... it has to be implemented.

**Comment by danielwwf** [comment]
It's now in but set to testnet via ?testnet=true

**Comment by t3nshi** [comment]
I will check again thanks for spotting it

**Comment by danielwwf** [comment]
fixed
