### ISSUE TITLE
[UI-FIX] Contacts entry in settings menu

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#76]
**Section or interface element**
Contacts entry in Settings Menu

**Description**
Change "Contacts contacts" to "Contacts"

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/92384426-5e2d0180-f110-11ea-88cc-060f5ad03954.png)

**Comment by t3nshi** [comment]
Right away

**Comment by danielwwf** [comment]
fixed
