### ISSUE TITLE
[UI-FIX] Contact Names

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#77]
**Section or interface element**
Contacts

**Description**
The contact name should be black and bold.

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/92384536-8ae11900-f110-11ea-94ef-89ac67b2e523.png)

**Comment by t3nshi** [comment]
Will be fixed for next version, also the send button is not visible right now, will be fixed then too.

**Comment by danielwwf** [comment]
looks the same for me in 0.5.2

**Comment by t3nshi** [comment]
Yes the fix apparently didn't came through i'm checking up what went wrong.

**Comment by danielwwf** [comment]
fixed
