### ISSUE TITLE
[BUG] Contacts glitch

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#78]
**Describe the bug**
If you go back and forth you end up with an "Add new" entry. If you restart the wallet and open the contacts again, its gone.

**To Reproduce**
1. Add a contact
2. Add a contact again
3. Add a contact again and remove one
4. Go to Contacts and see error

**Expected behavior**
The framed empty one shouldn't be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/92384875-21153f00-f111-11ea-9e28-fafb7c02b230.png)

**Smartphone (please complete the following information):**
 - Device: Not8
 - OS: Droid
 - OS Version 10
 - App Version 0.5.1

**Additional context**

**Comment by t3nshi** [comment]
Seems annoying, I will find out and solve ASAP

**Comment by danielwwf** [comment]
still the same in 0.5.2 on my note8

**Comment by t3nshi** [comment]
I found the issue... will be updated for next version

**Comment by danielwwf** [comment]
fixed
