### ISSUE TITLE
[UI-FIX]Operator Detail Page

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#80]
**Section or interface element**
Home -> Tap on operator

**Reason**
We need to give users a way to verify the link dir work, best by showing them the deposit address and dest tag that has been received by the backend and is stored under operator registrations.

**Description**
Add a button to the bottom or near the top of the details page, that reveal the details once a link did happen successfully.

**Comment by t3nshi** [comment]
Sounds about right. Let me check this out

**Comment by danielwwf** [comment]
Works, tutorial needs an update
