### ISSUE TITLE
[UI-FIX] additional text needed and layout change for buy/sell section

### ISSUE THREAD

**Issue by georgemac70cr8** [asgiom/cr8-brm-mobile-issues#82]
**Section or interface element**
BUY/SELL SECTION

**Reason**
We need to add some text to explain that people only have 7 days to sell back their cr8 that they buy in the app.

**Description**
Please add the following text:
"PLEASE NOTE: if you would like to sell back any CR8,
you must do so within 7 days of purchase." - **in orange text colour and centered.**

and below the "I  want to buy..." text box.

**The "I want to buy " text box needs to be moved up higher in the form.**

![photo_2020-09-10 11 25 56](https://user-images.githubusercontent.com/69824025/92721932-2075e600-f367-11ea-884f-9d36e84a0582.jpeg)

**Screenshots**
Illustrate current look and feel. Or provide commented pictures, or 
edited screens to see how it should look like. Be clear about which picture is edited

**Comment by t3nshi** [comment]
ok. we will include it in next release.

**Comment by t3nshi** [comment]
Did someone had a chance to check this?

**Comment by georgemac70cr8** [comment]
yes, it doesn't look great. Can you split the lines so there's approx equal numbner of chars per line?

also the 'additional information' doesn't look like a link

**Comment by t3nshi** [comment]
So I removed white space as you requested, but let me add a bit of padding and the additional information could be a button maybe so it stands out as a CTA...
![Screenshot 2020-09-15 at 11 53 47](https://user-images.githubusercontent.com/3123415/93241344-d5831680-f74a-11ea-8dc2-677739afc79c.png)

**Comment by georgemac70cr8** [comment]
it's more the split of the sentence... you have much more chars on line 1 than you do on line 2:

PLEASE NOTE:  if you would like to sell back your CR8, you must do so (69 chars)
within 7 days of purchase (25 chars)

please compare my screenshot to yours


[cid:92e5f232-9038-476f-9547-f0ab1768fa12]

________________________________

**Comment by t3nshi** [comment]
This is not a reliable way to make a change... since this is not going to fit the same way on different screens widths

**Comment by t3nshi** [comment]
![Screenshot 2020-09-15 at 12 29 52](https://user-images.githubusercontent.com/3123415/93244475-66f48780-f74f-11ea-9b85-291dc67c7f14.png)
![Screenshot 2020-09-15 at 12 30 27](https://user-images.githubusercontent.com/3123415/93244476-6825b480-f74f-11ea-8d09-9f3f7263aa90.png)
![Screenshot 2020-09-15 at 12 31 05](https://user-images.githubusercontent.com/3123415/93244479-6825b480-f74f-11ea-887b-e827049da958.png)
take a look so you get the idea

**Comment by georgemac70cr8** [comment]
i don't have the answers but i just don't know why you choose to have 69 chars on one line and 25 on another - you don't need to answer. Please just do whatever looks best, i can leave to your discretion and judgement thanks.

**Comment by t3nshi** [comment]
how about like this...
![Screenshot 2020-09-15 at 12 37 24](https://user-images.githubusercontent.com/3123415/93245028-4547d000-f750-11ea-9a8c-0beed7ea4037.png)

**Comment by georgemac70cr8** [comment]
yes, that looks much better thanks. Now i see what you're saying now with regards to screen size.

**Comment by t3nshi** [comment]
that's what I meant.... the screen is the one that decides about the chars.. I have no control about it... I just say let's make the text this big and aligned center or left... and it gets placed depending on the device screen size

**Comment by georgemac70cr8** [comment]
thank you, additional info button looks better - but can we move the button under the other 2 buttons - we don't want to distract from people making their buy.

**Comment by Mattch33** [comment]
Please can you just add a "." (full stop) a the end of the sentence. Then good to go. Thanks

**Comment by t3nshi** [comment]
Ok done. We will check on next version.

**Comment by danielwwf** [comment]
fixed
