### ISSUE TITLE
BUY / SELL FORM LAYOUT CHANGE

### ISSUE THREAD

**Issue by georgemac70cr8** [asgiom/cr8-brm-mobile-issues#84]
**Section or interface element**
I have put the buy/sell form UI requests as 2 separate issues. Feel free to do them at the same time if easier. It's just vitally important that the text is added (issue  #82) to the form and then these can be worked on. However, the text change in issue 82 should not be held up because of these layout changes in this request.

I have noticed that this form has lots of space / line breaks and areas which could be layed out better in order to have the 2 calls to action (get quote / payments) above the scroll. Where possible we should have all forms condensed to fit screen, with no scrolling required. That will be tricky on different phones but removing dead space could help.

**Reason**
The CTA buttons should feature higher up the form so that the UX is easier. To get the buttons higher we can reduce blank sections / extra line breaks, etc.

**Description**
Please see screenshots of how we can improve this form. We know that the app is evolving and we may not think of everything straight away. These changes make it easer for the user, ulimately. I hope this makes sense. It's a work in progress. 

![BUY:SELL FORM SHRINK](https://user-images.githubusercontent.com/69824025/92722835-79924980-f368-11ea-9b9e-c64e8044b7ee.png)

**Screenshots**
Illustrate current look and feel. Or provide commented pictures, or 
edited screens to see how it should look like. Be clear about which picture is edited

**Comment by t3nshi** [comment]
Ok I will check how we can  arrange this layout.

**Comment by t3nshi** [comment]
this is done already... can we validate is proper? so we can close this? or if not ,so we can make any adjustment for next version?
