### ISSUE TITLE
[BUG] Dark mode - Duration limits font should be white

### ISSUE THREAD

**Issue by ibanezvaio** [asgiom/cr8-brm-mobile-issues#86]
**Describe the bug**
Duration font colour should be white when viewing [Set Limits] in dark mode

**To Reproduce**
1. Go to Settings
2. Change theme to 'Dark'
3. Open hamburger menu
4. Tap [Set Limits]

**Expected behavior**
All font colours in dark mode should be white/light

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung S6
 - OS: Android
 - OS Version 7.0
 - App Version 0.5.2

![Screenshot_20200910-123845](https://user-images.githubusercontent.com/2853264/92724733-ffab9180-f362-11ea-88a0-fe349827116c.png)

**Comment by t3nshi** [comment]
Right, I'll check and figure this out

**Comment by danielwwf** [comment]
fixed.
