### ISSUE TITLE
[BUG]Adding a contact forwards to send page

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#87]
**Describe the bug**
If you add a contact you get redirect to the send page, while you should be taken to the contact list.

**To Reproduce**
1. Add a contact
2. See error

**Expected behavior**
After adding a contact you should be taken to the contact list.

**Smartphone (please complete the following information):**
 - Device: Note8
 - OS: Android
 - OS Version 10
 - App Version 0.5.2

**Additional context**

**Comment by t3nshi** [comment]
we should not put bugs on the already released version milestone, I would need Marty's Delorean for that.

**Comment by t3nshi** [comment]
I could confirm this... I will try to sort out what's going on and let you know a bit later

**Comment by danielwwf** [comment]
not fixed in 0.5.3

**Comment by t3nshi** [comment]
well actually you cannot check right now because of #92 so I would say instead that you could not test it at all...

**Comment by danielwwf** [comment]
not fixed in 0.5.4

**Comment by danielwwf** [comment]
fixed
