### ISSUE TITLE
[BUG] Problem editing contacts apparently producing  an ANR state 

### ISSUE THREAD

**Issue by ibanezvaio** [asgiom/cr8-brm-mobile-issues#88]
**Describe the bug**

**To Reproduce**
1. Go to Contacts - see first screenshot (only 1 contact)
2. Tap the edit button
3. Tap [Update Contact]
4. Open Contacts again
5. Note the rogue empty contact - second screenshot
6. Tap the [Send] button on the empty contact ( you'll be taken to a send screen with an address)
7. Open contacts again
8. Tap [Edit] button on the empty contact 

At this point the app should be unresponsive to any further navigation. Seems to be ANR state

![Screenshot_20200910-125736](https://user-images.githubusercontent.com/2853264/92726955-5070b980-f366-11ea-8414-fcfb51e75886.png)
![Screenshot_20200910-125751](https://user-images.githubusercontent.com/2853264/92748576-342c4700-f37d-11ea-9f50-e4bacf0e0ec4.png)

**Smartphone (please complete the following information):**
 - Device: Samsung S6
 - OS: Android
 - OS Version 7.0
 - App Version 0.5.2

**Comment by t3nshi** [comment]
I cannot see the 2nd screenshot, both look the same to me... the other thing is that the title is not very clear to me... can you help me understand what this issue is about?

**Comment by ibanezvaio** [comment]
@t3nshi you're absolutely right, I'd included the same screenshot twice - now fixed above. 

ANR = App not responding. The UI freezes and will not respond to further screen taps

**Comment by t3nshi** [comment]
thanks for the corrections

**Comment by t3nshi** [comment]
I could replicate the issue three times but the app continued responding... I left the ANR cause the aberrant behaviour might cause ANR on some devices, but updated the title to provide a more meaningful issue that would avoid duplicates.
It seems that a fix for other issue produced unintended side effects... I will update here 
as soon as I have something more useful.

**Comment by ibanezvaio** [comment]
FYI @t3nshi I could replicate this issue on iOS - iPhone XR iOS 14.0

**Comment by t3nshi** [comment]
I finally got it and now is solved for 5.0.3...

**Comment by t3nshi** [comment]
Can you please confirm the solution so we can close this?

**Comment by ibanezvaio** [comment]
Confirmed fixed in 0.5.4(1)
