### ISSUE TITLE
[BUG] Stuck on login with no way to log back in

### ISSUE THREAD

**Issue by ibanezvaio** [asgiom/cr8-brm-mobile-issues#89]
**Describe the bug**
It's possible to get into a state where you can't log back in after cancelling the pin from Obipis login

**To Reproduce**
1. Go to Buy/Sell
2. Cancel login - either biometric or pin
//An error is displayed here - see screenshot 1
3. Tap [Dismiss]
4. There is no way to log back in - [Cancel] does not respond - see screenshot 2

**Expected behavior**
[Cancel] should return the user to the app, maybe the home view?

screenshot 1
![image1](https://user-images.githubusercontent.com/2853264/92963434-56e85980-f46a-11ea-9e12-4f0a886cf5e1.png)

screenshot 2
![image0](https://user-images.githubusercontent.com/2853264/92963444-5b147700-f46a-11ea-86ac-75b29a05be3d.png)

 - Device: [e.g. iPhone XR]
 - OS: iOS
 - OS Version 15
 - App Version 0.5.2

**Comment by t3nshi** [comment]
I could replicate the issue, but only with biometric, when you cancel the biometric request. I will see how to let the user cancel this screen by just canceling the biometric request or letting him cancel with the cancel button after that. In android was enough to use the back button, but I don't know how to do that in ios. Maybe that's the blocker there.

**Comment by ibanezvaio** [comment]
Confirmed fixed in 0.5.4 - cancel button now takes me back into the app
