### ISSUE TITLE
Scan a QR Code does not clean destination tag

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#9]
**Describe the bug**
If you scan a QR code that has no desttag, while scanned one before that did have one, the desttag gets not cleared. If you scan two different QR codes with two different tags all is good.

**To Reproduce**
Scan this code: 
![image](https://user-images.githubusercontent.com/30388756/90522805-71315f00-e16c-11ea-94c7-a8fb38ba0b4d.png)
Desttag is 123456

Now scan this one:
![image](https://user-images.githubusercontent.com/30388756/90522865-860df280-e16c-11ea-8e71-ce48dad7f8dc.png)

Now scan this one:
![image](https://user-images.githubusercontent.com/30388756/90523083-c79e9d80-e16c-11ea-8d6f-fb62c1661857.png)

It still pulls the previous tag

**Expected behavior**
Should display the info read from the code and clear the tag if there is non.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Note8, S9+, 10 
 - OS: Android
 - OS Version 9 and newer
 - App Version 0.4.5

**Comment by t3nshi** [comment]
You are right! We are only changing the destination tag when there is one provided. I will fix this right away.

**Comment by danielwwf** [comment]
Is destination tag "0" the same as no tag? The previous tag gets replaced with "0". It should be empty.

**Comment by t3nshi** [comment]
Yes, 0 is the same as no tag in this case

**Comment by danielwwf** [comment]
People will be confused by this. If possible the field should be empty.

**Comment by danielwwf** [comment]
Nice one, fixed.
