### ISSUE TITLE
[BUG] cancelling login causes ANR

### ISSUE THREAD

**Issue by ibanezvaio** [asgiom/cr8-brm-mobile-issues#90]
**To Reproduce**
1. Open the app
2. If you have biometric login, ensure this fails (I was using faceID)
3. Tap cancel when asked to try again
4. App is seemingly in ANR state. Login and restore buttons are unresponsive 

**Expected behavior**
Login button should produce biometric or pin entry

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 
 - OS Version 14
 - App Version 0.5.2

**Additional context**

**Comment by t3nshi** [comment]
the problem also seems to happen if you just cancel the biometric request, even on android... this seems related to #89 and in android we can get away by just pressing the back button. It seems that the issue is related to fallback methods that should be provided by the OS... but I will find a way to overcome this kind of behaviour.

**Comment by ibanezvaio** [comment]
I need an iOS build to test this one

**Comment by ibanezvaio** [comment]
I can replicate in 0.5.4, iOS

**Comment by danielwwf** [comment]
On my Note8 the app gets very laggy when biometric is activated, there is also no way to use the pin instead.

**Comment by Mattch33** [comment]
Also causes a lot of lag on Android S9. Managed to log in but bio metric area remained. Only fix was restarting phone. 
![Screenshot_20200916-112902_CR8 Wallet](https://user-images.githubusercontent.com/65967421/93326371-97502a80-f810-11ea-9b73-b17abe4f0d7b.jpg)

**Comment by t3nshi** [comment]
I will try to test on some samsungs so we can sort this out.

**Comment by Mattch33** [comment]
Great stuff,

 

Thank You

 

Matt

**Comment by t3nshi** [comment]
Since we need to wait for App store to test this... I would move this to the next version

**Comment by ibanezvaio** [comment]
I can still replicate this in 0.5.6

**Comment by t3nshi** [comment]
Ok, I thought the fix was enough, any difference when you tested this on 0.5.6, or it behaves exactly the same?

**Comment by ibanezvaio** [comment]
Seems to behave exactly the same. No difference

**Comment by t-jacobi** [comment]
Couldn't reproduce the behavior. iOS 13.6.1, iPhone 6s, App 0.5.8

**Comment by t3nshi** [comment]
You mean it is fixed? if it is can you close it? if it isn can you please elaborate?

**Comment by ibanezvaio** [comment]
I can’t replicate this one in 0.5.9. Closing
