### ISSUE TITLE
[BUG]Wallet crash during setup

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#91]
**Describe the bug**
If you switch out during the setup, the setup will show a screen "Incomplete Setup". I think that's because the wallet is trying to auto lock itself.

**To Reproduce**
1. Start setup
2. Switch to a different app
3. Come back

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Note8
 - OS: Android
 - OS Version 10
 - App Version 0.5.3

**Additional context**

**Comment by t3nshi** [comment]
that sound annoying... let me check it out

**Comment by danielwwf** [comment]
fixed.
