### ISSUE TITLE
[BUG]Adding Contact button does not work

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#92]
**Describe the bug**
Add Contact button does nothing

**To Reproduce**
1. Go to Settings
2. Click on Contacts
3. Tap Add Contacts

**Expected behavior**
Should open a dialog to allow me adding a contact

**Smartphone (please complete the following information):**
 - Device: Note8
 - OS: Android
 - OS Version 10
 - App Version 0.5.3

**Additional context**

**Comment by t3nshi** [comment]
Sure I must have messed it up when i fixed the other annoying contacts bug... let me check this out

**Comment by whywefight** [comment]
does not work if no contact exists OR never existed
