### ISSUE TITLE
[BUG] Using contacts to send prefixes 'CSC' to account

### ISSUE THREAD

**Issue by ibanezvaio** [asgiom/cr8-brm-mobile-issues#94]
**Describe the bug**
When trying to send to a contact, 'CSC' is prefixed to the account

**To Reproduce**
1. Go to Contacts
2. Click on Send icon on one of the contacts - See screenshot

**Screenshots**
![Screenshot_20200915-212725](https://user-images.githubusercontent.com/2853264/93261421-92509400-f79a-11ea-8b20-071c49c588f8.png)

**Smartphone (please complete the following information):**
 - OS Version [e.g. 8.1]
 - App Version [e.g. 1.0.1]

**Additional context**

**Comment by danielwwf** [comment]
fixed pls confirm @ibanezvaio

**Comment by ibanezvaio** [comment]
Confirmed fixed in 0.5.4(1)
