### ISSUE TITLE
[BUG]White flickering on login when keypad is visible on iOS

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#95]
**Describe the bug**
The login screen flashes when the keypad is visible. Login and KYC

**To Reproduce**
1. Login on an iPhone 6s

**Expected behavior**
Should not flash

**Screenshots**
check slack development channel for video

**Smartphone (please complete the following information):**
 - Device: iPhone6
 - OS: iOS
 - OS Version 13.7
 - App Version 0.5.4 2nd

**Additional context**

**Comment by t3nshi** [comment]
I just want to confirm, You only found this behaviour  when the keypad opens right? can you check if it happens all the time the PIN is asked happens? for example checking the seed and making transactions?

**Comment by danielwwf** [comment]
still exists in 0.5.5, it's only happening when a full keypad is shown during entering a pin.

1. Login
2. Confirming TX
3. Login to buy/sell

**Comment by t3nshi** [comment]
Ok. We will need to try again. We managed to reproduce the flickering in the simulator under some specific settings, but our fix took away the flashing.... of course, what worked for the simulator might not worked for the actual device...

**Comment by t3nshi** [comment]
My bad... it seems that my fixed was not very complete. This one I think works better.

**Comment by danielwwf** [comment]
fixed.
