### ISSUE TITLE
[BUG]Sending from Contact does not work

### ISSUE THREAD

**Issue by danielwwf** [asgiom/cr8-brm-mobile-issues#97]
**Describe the bug**
If you try to trigger a transaction from the contacts on Android, nothing happens. Works fine on iOS

**To Reproduce**
1. Go to Contacts and create one
2. Click on the wallet item

**Expected behavior**
Should switch to send and put the address in like on iOS

**Screenshots**
![image](https://user-images.githubusercontent.com/30388756/93279844-909dc500-f7c8-11ea-8050-3d4ca8dbfab4.png)

**Smartphone (please complete the following information):**
 - Device: Moto G7 play
 - OS: Android
 - OS Version 10
 - App Version 0.5.4 2nd

**Additional context**

**Comment by t3nshi** [comment]
I will try to reproduce, on my first try it worked... weird... maybe with 10 version? I will let you know as soon as I know more.

**Comment by ajochems** [comment]
Just tried on a Moto 9 and a Huawei P8 and i can not reproduce the issue.

**Comment by t3nshi** [comment]
I could test this on samsung s4, moto z2 force, moto g7 power, lenovo k5 and sony A4. We will need you to test this again on version 0.5.5 and maybe provide a bit more details so we can fix it.

**Comment by danielwwf** [comment]
fixed :)
