### ISSUE TITLE
[BUG] Part of email is missing in Dark Mode only

### ISSUE THREAD

**Issue by ibanezvaio** [asgiom/cr8-brm-mobile-issues#98]
**Describe the bug**
When veiwing Seed words in Dark Mode, part of my email address is missing

**To Reproduce**
1. Go toHamburger menu
2. Click on Settings - ensure Dark theme is selected
3. Tap [Show See Words]
4. Allow pin or biometric
5. the 'rg' tld of my email is not displayed (it is there in full in Light theme) - should be andy@casinocoin.org

**Expected behavior**
My full email address to be displayed

**Screenshots**
![image0 (1)](https://user-images.githubusercontent.com/2853264/93326903-789e6380-f811-11ea-86a6-846e3d5ccdbc.png)

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS
 - OS Version 14.0
 - App Version 0.5.4

**Additional context**

**Comment by t3nshi** [comment]
there were some issues with the styles and they were affecting also light theme... But they should be ok on next version.

**Comment by t3nshi** [comment]
We checked on several devices but since it can pass some time until you can check on ios and validate since we will have to wait for App store to push the new version, then I will move this for next version for now.

**Comment by ibanezvaio** [comment]
Fixed in 0.5.6
