### ISSUE TITLE
[UI-FIX] Email "Asociated" fix spelling

### ISSUE THREAD

**Issue by ibanezvaio** [asgiom/cr8-brm-mobile-issues#99]
**Section or interface element**
Go to [Settings] -> show seed words 

**Reason**
The spelling 'Asociated' is incorrectly spelling - should be "Associated"

![image0 (1)](https://user-images.githubusercontent.com/2853264/93327219-eea2ca80-f811-11ea-9354-6bcc36850b1a.png)

**Comment by t3nshi** [comment]
sure, you're right... I don't know how long this passed unnoticed. Thanks!

**Comment by danielwwf** [comment]
fixed
